# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/github_organization_role_team_assignment/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GithubOrganizationRoleTeamAssignment
    include Pangea::Resources::ResourceBuilder

    define_resource :github_organization_role_team_assignment,
      attributes_class: Github::Types::OrganizationRoleTeamAssignmentAttributes,
      outputs: { id: :id },
      map: [:role_id, :team_slug]
  end
  module Github
    include GithubOrganizationRoleTeamAssignment
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Github)
