# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/github_branch/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GithubBranch
    include Pangea::Resources::ResourceBuilder

    define_resource :github_branch,
      attributes_class: Github::Types::BranchAttributes,
      outputs: { id: :id },
      map: [:branch, :repository],
      map_present: [:etag, :source_branch, :source_sha]
  end
  module Github
    include GithubBranch
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Github)
