# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/github_team_sync_group_mapping/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GithubTeamSyncGroupMapping
    include Pangea::Resources::ResourceBuilder

    define_resource :github_team_sync_group_mapping,
      attributes_class: Github::Types::TeamSyncGroupMappingAttributes,
      outputs: { id: :id },
      map: [:team_slug],
      map_present: [:group]
  end
  module Github
    include GithubTeamSyncGroupMapping
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Github)
