# Code generated by pangea-forge.
# InSpec profile for verifying github_actions_organization_variable_repositories infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set GITHUB_TOKEN and GITHUB_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/github_actions_organization_variable_repositories/ -t github://

control 'github_actions_organization_variable_repositories-exists' do
  impact 1.0
  title 'Manages a github_actions_organization_variable_repositories resource'
  desc 'Verify that the github_actions_organization_variable_repositories resource exists and has expected properties'

  describe github_actions_organization_variable_repositories(name: attribute('id')) do
    it { should exist }
    its('selected_repository_ids') { should_not be_nil }
    its('variable_name') { should_not be_nil }
  end
end
