# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/github_issue_labels/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GithubIssueLabels
    include Pangea::Resources::ResourceBuilder

    define_resource :github_issue_labels,
      attributes_class: Github::Types::IssueLabelsAttributes,
      outputs: { id: :id },
      map: [:repository],
      map_present: [:label]
  end
  module Github
    include GithubIssueLabels
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Github)
