# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/github_emu_group_mapping/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GithubEmuGroupMapping
    include Pangea::Resources::ResourceBuilder

    define_resource :github_emu_group_mapping,
      attributes_class: Github::Types::EmuGroupMappingAttributes,
      outputs: { id: :id },
      map: [:group_id, :team_slug]
  end
  module Github
    include GithubEmuGroupMapping
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Github)
