# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Github::Types
  include Dry.Types()

  class EmuGroupMappingAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Github::Types

    attribute :group_id, (T::Coercible::Integer | T::Coercible::Float)
    attribute :team_slug, T::String
  end
end
