# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/github_dependabot_secret/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GithubDependabotSecret
    include Pangea::Resources::ResourceBuilder

    define_resource :github_dependabot_secret,
      attributes_class: Github::Types::DependabotSecretAttributes,
      outputs: { id: :id },
      map: [:repository, :secret_name],
      map_present: [:encrypted_value, :plaintext_value]
  end
  module Github
    include GithubDependabotSecret
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Github)
