# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Github::Types
  include Dry.Types()

  class BranchProtectionV3Attributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Github::Types

    attribute :branch, T::String
    attribute :repository, T::String
    attribute? :enforce_admins, T::Bool.optional
    attribute? :require_conversation_resolution, T::Bool.optional
    attribute? :require_signed_commits, T::Bool.optional
    attribute? :required_pull_request_reviews, T::Array.of(T::Hash).optional
    attribute? :required_status_checks, T::Array.of(T::Hash).optional
    attribute? :restrictions, T::Array.of(T::Hash).optional
  end
end
