# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Github::Types
  include Dry.Types()

  class ProjectCardAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Github::Types

    attribute :column_id, T::String
    attribute? :content_id, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :content_type, T::String.optional
    attribute? :note, T::String.optional
  end
end
