# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Github::Types
  include Dry.Types()

  class EnterpriseActionsPermissionsAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Github::Types

    attribute :enabled_organizations, T::String
    attribute :enterprise_slug, T::String
    attribute? :allowed_actions, T::String.optional
    attribute? :allowed_actions_config, T::Hash.optional
    attribute? :enabled_organizations_config, T::Hash.optional
  end
end
