# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Github::Types
  include Dry.Types()

  class EnterpriseActionsPermissionsAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Github::Types

    attribute :enabled_organizations, T::String
    attribute :enterprise_slug, T::String
    attribute? :allowed_actions, T::String.optional
    attribute? :allowed_actions_config, T::Array.of(T::Hash).optional
    attribute? :enabled_organizations_config, T::Array.of(T::Hash).optional
  end
end
