# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/github_repository_pull_request/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GithubRepositoryPullRequest
    include Pangea::Resources::ResourceBuilder

    define_resource :github_repository_pull_request,
      attributes_class: Github::Types::RepositoryPullRequestAttributes,
      outputs: { id: :id },
      map: [:base_ref, :base_repository, :head_ref, :title],
      map_present: [:body, :owner],
      map_bool: [:maintainer_can_modify]
  end
  module Github
    include GithubRepositoryPullRequest
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Github)
