# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Github::Types
  include Dry.Types()

  class RepositoryPullRequestAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Github::Types

    attribute :base_ref, T::String
    attribute :base_repository, T::String
    attribute :head_ref, T::String
    attribute :title, T::String
    attribute? :body, T::String.optional
    attribute? :maintainer_can_modify, T::Bool.optional
    attribute? :owner, T::String.optional
  end
end
