# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Github::Types
  include Dry.Types()

  class RepositoryPullRequestAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Github::Types

    attribute :base_ref, T::String
    attribute :base_repository, T::String
    attribute :head_ref, T::String
    attribute :title, T::String
    attribute? :body, T::String.optional
    attribute? :maintainer_can_modify, T::Bool.optional
    attribute? :owner, T::String.optional
  end
end
