# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/github_branch_protection/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GithubBranchProtection
    include Pangea::Resources::ResourceBuilder

    define_resource :github_branch_protection,
      attributes_class: Github::Types::BranchProtectionAttributes,
      outputs: { id: :id },
      map: [:pattern, :repository_id],
      map_present: [:force_push_bypassers, :required_pull_request_reviews, :required_status_checks, :restrict_pushes],
      map_bool: [:allows_deletions, :allows_force_pushes, :enforce_admins, :lock_branch, :require_conversation_resolution, :require_signed_commits, :required_linear_history]
  end
  module Github
    include GithubBranchProtection
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Github)
