# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Github::Types
  include Dry.Types()

  class BranchProtectionAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Github::Types

    attribute :pattern, T::String
    attribute :repository_id, T::String
    attribute? :allows_deletions, T::Bool.optional
    attribute? :allows_force_pushes, T::Bool.optional
    attribute? :enforce_admins, T::Bool.optional
    attribute? :force_push_bypassers, T::Array.of(T::String).optional
    attribute? :lock_branch, T::Bool.optional
    attribute? :require_conversation_resolution, T::Bool.optional
    attribute? :require_signed_commits, T::Bool.optional
    attribute? :required_linear_history, T::Bool.optional
    attribute? :required_pull_request_reviews, T::Array.of(T::Hash).optional
    attribute? :required_status_checks, T::Array.of(T::Hash).optional
    attribute? :restrict_pushes, T::Array.of(T::Hash).optional
  end
end
