# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/github_actions_organization_secret_repository/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GithubActionsOrganizationSecretRepository
    include Pangea::Resources::ResourceBuilder

    define_resource :github_actions_organization_secret_repository,
      attributes_class: Github::Types::ActionsOrganizationSecretRepositoryAttributes,
      outputs: { id: :id },
      map: [:repository_id, :secret_name]
  end
  module Github
    include GithubActionsOrganizationSecretRepository
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Github)
