# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Github::Types
  include Dry.Types()

  class ActionsOrganizationSecretRepositoryAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Github::Types

    attribute :repository_id, (T::Coercible::Integer | T::Coercible::Float)
    attribute :secret_name, T::String
  end
end
