# Code generated by pangea-forge.
# InSpec profile for verifying github_organization_role_user infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set GITHUB_TOKEN and GITHUB_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/github_organization_role_user/ -t github://

control 'github_organization_role_user-exists' do
  impact 1.0
  title 'Manages a github_organization_role_user resource'
  desc 'Verify that the github_organization_role_user resource exists and has expected properties'

  describe github_organization_role_user(name: attribute('id')) do
    it { should exist }
    its('login') { should_not be_nil }
    its('role_id') { should_not be_nil }
  end
end
