# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/github_repository_autolink_reference/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GithubRepositoryAutolinkReference
    include Pangea::Resources::ResourceBuilder

    define_resource :github_repository_autolink_reference,
      attributes_class: Github::Types::RepositoryAutolinkReferenceAttributes,
      outputs: { id: :id },
      map: [:key_prefix, :repository, :target_url_template],
      map_bool: [:is_alphanumeric]
  end
  module Github
    include GithubRepositoryAutolinkReference
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Github)
