# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Github::Types
  include Dry.Types()

  class RepositoryAutolinkReferenceAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Github::Types

    attribute :key_prefix, T::String
    attribute :repository, T::String
    attribute :target_url_template, T::String
    attribute? :is_alphanumeric, T::Bool.optional
  end
end
