# Code generated by pangea-forge.
# InSpec profile for verifying github_app_installation_repository infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set GITHUB_TOKEN and GITHUB_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/github_app_installation_repository/ -t github://

control 'github_app_installation_repository-exists' do
  impact 1.0
  title 'Manages a github_app_installation_repository resource'
  desc 'Verify that the github_app_installation_repository resource exists and has expected properties'

  describe github_app_installation_repository(name: attribute('id')) do
    it { should exist }
    its('installation_id') { should_not be_nil }
    its('repository') { should_not be_nil }
  end
end
