# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/github_actions_organization_variable/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GithubActionsOrganizationVariable
    include Pangea::Resources::ResourceBuilder

    define_resource :github_actions_organization_variable,
      attributes_class: Github::Types::ActionsOrganizationVariableAttributes,
      outputs: { id: :id },
      map: [:value, :variable_name, :visibility],
      map_present: [:selected_repository_ids]
  end
  module Github
    include GithubActionsOrganizationVariable
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Github)
