# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Github::Types
  include Dry.Types()

  class ActionsOrganizationVariableAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Github::Types

    attribute :value, T::String
    attribute :variable_name, T::String
    attribute :visibility, T::String
    attribute? :selected_repository_ids, T::Array.of((T::Coercible::Integer | T::Coercible::Float)).optional
  end
end
