# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/github_dependabot_organization_secret/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GithubDependabotOrganizationSecret
    include Pangea::Resources::ResourceBuilder

    define_resource :github_dependabot_organization_secret,
      attributes_class: Github::Types::DependabotOrganizationSecretAttributes,
      outputs: { id: :id },
      map: [:secret_name, :visibility],
      map_present: [:encrypted_value, :key_id, :plaintext_value, :selected_repository_ids]
  end
  module Github
    include GithubDependabotOrganizationSecret
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Github)
