# Code generated by pangea-forge.
# InSpec profile for verifying github_repository_pull_request infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set GITHUB_TOKEN and GITHUB_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/github_repository_pull_request/ -t github://

control 'github_repository_pull_request-exists' do
  impact 1.0
  title 'Manages a github_repository_pull_request resource'
  desc 'Verify that the github_repository_pull_request resource exists and has expected properties'

  describe github_repository_pull_request(name: attribute('id')) do
    it { should exist }
    its('base_ref') { should_not be_nil }
    its('base_repository') { should_not be_nil }
    its('head_ref') { should_not be_nil }
    its('title') { should_not be_nil }
  end
end
