# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/github_repository_environment/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GithubRepositoryEnvironment
    include Pangea::Resources::ResourceBuilder

    define_resource :github_repository_environment,
      attributes_class: Github::Types::RepositoryEnvironmentAttributes,
      outputs: { id: :id },
      map: [:environment, :repository],
      map_present: [:deployment_branch_policy, :reviewers, :wait_timer],
      map_bool: [:can_admins_bypass, :prevent_self_review]
  end
  module Github
    include GithubRepositoryEnvironment
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Github)
