# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Github::Types
  include Dry.Types()

  class RepositoryEnvironmentAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Github::Types

    attribute :environment, T::String
    attribute :repository, T::String
    attribute? :can_admins_bypass, T::Bool.optional
    attribute? :deployment_branch_policy, T::Array.of(T::Hash).optional
    attribute? :prevent_self_review, T::Bool.optional
    attribute? :reviewers, T::Array.of(T::Hash).optional
    attribute? :wait_timer, T::Float.optional
  end
end
