# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Github::Types
  include Dry.Types()

  class RepositoryEnvironmentDeploymentPolicyAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Github::Types

    attribute :environment, T::String
    attribute :repository, T::String
    attribute? :branch_pattern, T::String.optional
    attribute? :tag_pattern, T::String.optional
  end
end
