# Code generated by pangea-forge.
# InSpec profile for verifying github_organization_webhook infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set GITHUB_TOKEN and GITHUB_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/github_organization_webhook/ -t github://

control 'github_organization_webhook-exists' do
  impact 1.0
  title 'Manages a github_organization_webhook resource'
  desc 'Verify that the github_organization_webhook resource exists and has expected properties'

  describe github_organization_webhook(name: attribute('id')) do
    it { should exist }
    its('events') { should_not be_nil }
  end
end
