# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/github_user_gpg_key/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GithubUserGpgKey
    include Pangea::Resources::ResourceBuilder

    define_resource :github_user_gpg_key,
      attributes_class: Github::Types::UserGpgKeyAttributes,
      outputs: { id: :id },
      map: [:armored_public_key]
  end
  module Github
    include GithubUserGpgKey
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Github)
