# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/github_app_installation_repository/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GithubAppInstallationRepository
    include Pangea::Resources::ResourceBuilder

    define_resource :github_app_installation_repository,
      attributes_class: Github::Types::AppInstallationRepositoryAttributes,
      outputs: { id: :id },
      map: [:installation_id, :repository]
  end
  module Github
    include GithubAppInstallationRepository
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Github)
