# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Github::Types
  include Dry.Types()

  class RepositoryWebhookAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Github::Types

    attribute :events, T::Array.of(T::String)
    attribute :repository, T::String
    attribute? :active, T::Bool.optional
    attribute? :configuration, T::Hash.optional
    attribute? :etag, T::String.optional
  end
end
