# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Github::Types
  include Dry.Types()

  class RepositoryWebhookAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Github::Types

    attribute :events, T::Array.of(T::String)
    attribute :repository, T::String
    attribute? :active, T::Bool.optional
    attribute? :configuration, T::Array.of(T::Hash).optional
  end
end
