# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Github::Types
  include Dry.Types()

  class RepositoryDeploymentBranchPolicyAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Github::Types

    attribute :environment_name, T::String
    attribute :name, T::String
    attribute :repository, T::String
    attribute? :etag, T::String.optional
  end
end
