# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/github_user_ssh_key/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GithubUserSshKey
    include Pangea::Resources::ResourceBuilder

    define_resource :github_user_ssh_key,
      attributes_class: Github::Types::UserSshKeyAttributes,
      outputs: { id: :id },
      map: [:key, :title]
  end
  module Github
    include GithubUserSshKey
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Github)
