# Code generated by pangea-forge.
# InSpec profile for verifying github_repository_custom_property infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set GITHUB_TOKEN and GITHUB_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/github_repository_custom_property/ -t github://

control 'github_repository_custom_property-exists' do
  impact 1.0
  title 'Manages a github_repository_custom_property resource'
  desc 'Verify that the github_repository_custom_property resource exists and has expected properties'

  describe github_repository_custom_property(name: attribute('id')) do
    it { should exist }
    its('property_name') { should_not be_nil }
    its('property_type') { should_not be_nil }
    its('property_value') { should_not be_nil }
    its('repository') { should_not be_nil }
  end
end
