# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/github_team_settings/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GithubTeamSettings
    include Pangea::Resources::ResourceBuilder

    define_resource :github_team_settings,
      attributes_class: Github::Types::TeamSettingsAttributes,
      outputs: { id: :id },
      map: [:team_id],
      map_present: [:review_request_delegation]
  end
  module Github
    include GithubTeamSettings
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Github)
