# Code generated by pangea-forge.
# InSpec profile for verifying github_enterprise_organization infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set GITHUB_TOKEN and GITHUB_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/github_enterprise_organization/ -t github://

control 'github_enterprise_organization-exists' do
  impact 1.0
  title 'Manages a github_enterprise_organization resource'
  desc 'Verify that the github_enterprise_organization resource exists and has expected properties'

  describe github_enterprise_organization(name: attribute('id')) do
    it { should exist }
    its('admin_logins') { should_not be_nil }
    its('billing_email') { should_not be_nil }
    its('enterprise_id') { should_not be_nil }
    its('name') { should_not be_nil }
  end
end
