# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Github::Types
  include Dry.Types()

  class ActionsSecretAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Github::Types

    attribute :repository, T::String
    attribute :secret_name, T::String
    attribute? :destroy_on_drift, T::Bool.optional
    attribute? :encrypted_value, T::String.optional
    attribute? :plaintext_value, T::String.optional
  end
end
