# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/github_user_invitation_accepter/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GithubUserInvitationAccepter
    include Pangea::Resources::ResourceBuilder

    define_resource :github_user_invitation_accepter,
      attributes_class: Github::Types::UserInvitationAccepterAttributes,
      outputs: { id: :id },
      map_present: [:invitation_id],
      map_bool: [:allow_empty_id]
  end
  module Github
    include GithubUserInvitationAccepter
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Github)
