# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Github::Types
  include Dry.Types()

  class UserInvitationAccepterAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Github::Types

    attribute? :allow_empty_id, T::Bool.optional
    attribute? :invitation_id, T::String.optional
  end
end
