# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/github_actions_environment_secret/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GithubActionsEnvironmentSecret
    include Pangea::Resources::ResourceBuilder

    define_resource :github_actions_environment_secret,
      attributes_class: Github::Types::ActionsEnvironmentSecretAttributes,
      outputs: { id: :id },
      map: [:environment, :repository, :secret_name],
      map_present: [:encrypted_value, :plaintext_value]
  end
  module Github
    include GithubActionsEnvironmentSecret
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Github)
