# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/github_team/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GithubTeam
    include Pangea::Resources::ResourceBuilder

    define_resource :github_team,
      attributes_class: Github::Types::TeamAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:description, :ldap_dn, :notification_setting, :parent_team_id, :privacy],
      map_bool: [:create_default_maintainer]
  end
  module Github
    include GithubTeam
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Github)
