# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Github::Types
  include Dry.Types()

  class TeamAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Github::Types

    attribute :name, T::String
    attribute? :create_default_maintainer, T::Bool.optional
    attribute? :description, T::String.optional
    attribute? :ldap_dn, T::String.optional
    attribute? :notification_setting, T::String.optional
    attribute? :parent_team_id, T::String.optional
    attribute? :privacy, T::String.optional
  end
end
