# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Github::Types
  include Dry.Types()

  class TeamAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Github::Types

    attribute :name, T::String
    attribute? :create_default_maintainer, T::Bool.optional
    attribute? :description, T::String.optional
    attribute? :ldap_dn, T::String.optional
    attribute? :notification_setting, T::String.optional
    attribute? :parent_team_id, T::String.optional
    attribute? :parent_team_read_id, T::String.optional
    attribute? :parent_team_read_slug, T::String.optional
    attribute? :privacy, T::String.optional
  end
end
