# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/github_issue/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GithubIssue
    include Pangea::Resources::ResourceBuilder

    define_resource :github_issue,
      attributes_class: Github::Types::IssueAttributes,
      outputs: { id: :id },
      map: [:repository, :title],
      map_present: [:assignees, :body, :labels, :milestone_number]
  end
  module Github
    include GithubIssue
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Github)
