# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Github::Types
  include Dry.Types()

  class IssueAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Github::Types

    attribute :repository, T::String
    attribute :title, T::String
    attribute? :assignees, T::Array.of(T::String).optional
    attribute? :body, T::String.optional
    attribute? :labels, T::Array.of(T::String).optional
    attribute? :milestone_number, T::Float.optional
  end
end
