# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Github::Types
  include Dry.Types()

  class IssueAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Github::Types

    attribute :repository, T::String
    attribute :title, T::String
    attribute? :assignees, T::Array.of(T::String).optional
    attribute? :body, T::String.optional
    attribute? :labels, T::Array.of(T::String).optional
    attribute? :milestone_number, (T::Coercible::Integer | T::Coercible::Float).optional
  end
end
