# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/github_organization_custom_properties/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GithubOrganizationCustomProperties
    include Pangea::Resources::ResourceBuilder

    define_resource :github_organization_custom_properties,
      attributes_class: Github::Types::OrganizationCustomPropertiesAttributes,
      outputs: { id: :id },
      map: [:property_name],
      map_present: [:value_type],
      map_bool: [:required]
  end
  module Github
    include GithubOrganizationCustomProperties
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Github)
