# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Github::Types
  include Dry.Types()

  class OrganizationCustomPropertiesAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Github::Types

    attribute :property_name, T::String
    attribute? :required, T::Bool.optional
    attribute? :value_type, T::String.optional
  end
end
