# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Github::Types
  include Dry.Types()

  class OrganizationCustomPropertiesAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Github::Types

    attribute :property_name, T::String
    attribute? :allowed_values, T::Array.of(T::String).optional
    attribute? :default_value, T::String.optional
    attribute? :description, T::String.optional
    attribute? :required, T::Bool.optional
    attribute? :value_type, T::String.optional
    attribute? :values_editable_by, T::String.optional
  end
end
