# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/github_codespaces_user_secret/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GithubCodespacesUserSecret
    include Pangea::Resources::ResourceBuilder

    define_resource :github_codespaces_user_secret,
      attributes_class: Github::Types::CodespacesUserSecretAttributes,
      outputs: { id: :id },
      map: [:secret_name],
      map_present: [:encrypted_value, :plaintext_value, :selected_repository_ids]
  end
  module Github
    include GithubCodespacesUserSecret
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Github)
