# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Github::Types
  include Dry.Types()

  class CodespacesUserSecretAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Github::Types

    attribute :secret_name, T::String
    attribute? :encrypted_value, T::String.optional
    attribute? :plaintext_value, T::String.optional
    attribute? :selected_repository_ids, T::Array.of((T::Coercible::Integer | T::Coercible::Float)).optional
  end
end
