# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Github::Types
  include Dry.Types()

  class CodespacesUserSecretAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Github::Types

    attribute :secret_name, T::String
    attribute? :encrypted_value, T::String.optional
    attribute? :plaintext_value, T::String.optional
    attribute? :selected_repository_ids, T::Array.of(T::Float).optional
  end
end
