# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/github_actions_organization_oidc_subject_claim_customization_template/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GithubActionsOrganizationOidcSubjectClaimCustomizationTemplate
    include Pangea::Resources::ResourceBuilder

    define_resource :github_actions_organization_oidc_subject_claim_customization_template,
      attributes_class: Github::Types::ActionsOrganizationOidcSubjectClaimCustomizationTemplateAttributes,
      outputs: { id: :id },
      map: [:include_claim_keys]
  end
  module Github
    include GithubActionsOrganizationOidcSubjectClaimCustomizationTemplate
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Github)
