# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/github_repository_milestone/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GithubRepositoryMilestone
    include Pangea::Resources::ResourceBuilder

    define_resource :github_repository_milestone,
      attributes_class: Github::Types::RepositoryMilestoneAttributes,
      outputs: { id: :id },
      map: [:owner, :repository, :title],
      map_present: [:description, :due_date, :state]
  end
  module Github
    include GithubRepositoryMilestone
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Github)
