# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Github::Types
  include Dry.Types()

  class RepositoryMilestoneAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Github::Types

    attribute :owner, T::String
    attribute :repository, T::String
    attribute :title, T::String
    attribute? :description, T::String.optional
    attribute? :due_date, T::String.optional
    attribute? :state, T::String.optional
  end
end
