# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Github::Types
  include Dry.Types()

  class RepositoryMilestoneAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Github::Types

    attribute :owner, T::String
    attribute :repository, T::String
    attribute :title, T::String
    attribute? :description, T::String.optional
    attribute? :due_date, T::String.optional
    attribute? :state, T::String.optional
  end
end
