# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/github_enterprise_actions_runner_group/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GithubEnterpriseActionsRunnerGroup
    include Pangea::Resources::ResourceBuilder

    define_resource :github_enterprise_actions_runner_group,
      attributes_class: Github::Types::EnterpriseActionsRunnerGroupAttributes,
      outputs: { id: :id },
      map: [:enterprise_slug, :name, :visibility],
      map_present: [:selected_organization_ids, :selected_workflows],
      map_bool: [:allows_public_repositories, :restricted_to_workflows]
  end
  module Github
    include GithubEnterpriseActionsRunnerGroup
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Github)
