# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Github::Types
  include Dry.Types()

  class EnterpriseActionsRunnerGroupAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Github::Types

    attribute :enterprise_slug, T::String
    attribute :name, T::String
    attribute :visibility, T::String
    attribute? :allows_public_repositories, T::Bool.optional
    attribute? :restricted_to_workflows, T::Bool.optional
    attribute? :selected_organization_ids, T::Array.of(T::Float).optional
    attribute? :selected_workflows, T::Array.of(T::String).optional
  end
end
