# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/github_team_members/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GithubTeamMembers
    include Pangea::Resources::ResourceBuilder

    define_resource :github_team_members,
      attributes_class: Github::Types::TeamMembersAttributes,
      outputs: { id: :id },
      map: [:members, :team_id]
  end
  module Github
    include GithubTeamMembers
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Github)
