# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Github::Types
  include Dry.Types()

  class TeamMembersAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Github::Types

    attribute :members, T::Array.of(T::Hash)
    attribute :team_id, T::String
  end
end
