# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/github_organization_settings/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GithubOrganizationSettings
    include Pangea::Resources::ResourceBuilder

    define_resource :github_organization_settings,
      attributes_class: Github::Types::OrganizationSettingsAttributes,
      outputs: { id: :id },
      map: [:billing_email],
      map_present: [:blog, :company, :default_repository_permission, :description, :email, :location, :name, :twitter_username],
      map_bool: [:advanced_security_enabled_for_new_repositories, :dependabot_alerts_enabled_for_new_repositories, :dependabot_security_updates_enabled_for_new_repositories, :dependency_graph_enabled_for_new_repositories, :has_organization_projects, :has_repository_projects, :members_can_create_internal_repositories, :members_can_create_pages, :members_can_create_private_pages, :members_can_create_private_repositories, :members_can_create_public_pages, :members_can_create_public_repositories, :members_can_create_repositories, :members_can_fork_private_repositories, :secret_scanning_enabled_for_new_repositories, :secret_scanning_push_protection_enabled_for_new_repositories, :web_commit_signoff_required]
  end
  module Github
    include GithubOrganizationSettings
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Github)
