# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Github::Types
  include Dry.Types()

  class OrganizationSettingsAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Github::Types

    attribute :billing_email, T::String
    attribute? :advanced_security_enabled_for_new_repositories, T::Bool.optional
    attribute? :blog, T::String.optional
    attribute? :company, T::String.optional
    attribute? :default_repository_permission, T::String.optional
    attribute? :dependabot_alerts_enabled_for_new_repositories, T::Bool.optional
    attribute? :dependabot_security_updates_enabled_for_new_repositories, T::Bool.optional
    attribute? :dependency_graph_enabled_for_new_repositories, T::Bool.optional
    attribute? :description, T::String.optional
    attribute? :email, T::String.optional
    attribute? :has_organization_projects, T::Bool.optional
    attribute? :has_repository_projects, T::Bool.optional
    attribute? :location, T::String.optional
    attribute? :members_can_create_internal_repositories, T::Bool.optional
    attribute? :members_can_create_pages, T::Bool.optional
    attribute? :members_can_create_private_pages, T::Bool.optional
    attribute? :members_can_create_private_repositories, T::Bool.optional
    attribute? :members_can_create_public_pages, T::Bool.optional
    attribute? :members_can_create_public_repositories, T::Bool.optional
    attribute? :members_can_create_repositories, T::Bool.optional
    attribute? :members_can_fork_private_repositories, T::Bool.optional
    attribute? :name, T::String.optional
    attribute? :secret_scanning_enabled_for_new_repositories, T::Bool.optional
    attribute? :secret_scanning_push_protection_enabled_for_new_repositories, T::Bool.optional
    attribute? :twitter_username, T::String.optional
    attribute? :web_commit_signoff_required, T::Bool.optional
  end
end
