# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/github_project_column/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GithubProjectColumn
    include Pangea::Resources::ResourceBuilder

    define_resource :github_project_column,
      attributes_class: Github::Types::ProjectColumnAttributes,
      outputs: { id: :id },
      map: [:name, :project_id]
  end
  module Github
    include GithubProjectColumn
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Github)
