# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

RSpec.shared_examples 'a generated pangea resource' do |resource_type:, method:, required_attrs:, expected_outputs:, sensitive_fields: [], immutable_fields: [], boolean_fields: []|
  include Pangea::Testing::SynthesisTestHelpers

  it 'synthesizes valid Terraform JSON' do
    synth = create_synthesizer
    synth.extend(described_class)
    synth.send(method, 'test', required_attrs)
    result = normalize_synthesis(synth.synthesis)
    validate_terraform_structure(result, :resource)
    validate_resource_structure(result, resource_type.to_s, 'test')
  end

  it 'returns a ResourceReference' do
    synth = create_synthesizer
    synth.extend(described_class)
    ref = synth.send(method, 'test', required_attrs)
    expect(ref).to be_a(Pangea::Resources::ResourceReference)
    expect(ref.resource_type).to eq(resource_type)
  end

  it 'provides expected outputs' do
    synth = create_synthesizer
    synth.extend(described_class)
    ref = synth.send(method, 'test', required_attrs)
    expected_outputs.each do |output|
      expect(ref).to respond_to(output)
    end
  end

  it 'validates required attributes present' do
    synth = create_synthesizer
    synth.extend(described_class)
    synth.send(method, 'test', required_attrs)
    result = normalize_synthesis(synth.synthesis)
    config = validate_resource_structure(result, resource_type.to_s, 'test')
    validate_required_attributes(config, required_attrs.keys)
  end

  unless sensitive_fields.empty?
    it 'documents sensitive fields' do
      expect(sensitive_fields).to all(be_a(Symbol))
    end
  end

  unless immutable_fields.empty?
    it 'documents immutable fields' do
      expect(immutable_fields).to all(be_a(Symbol))
    end
  end

  boolean_fields.each do |field|
    [true, false].each do |val|
      it "accepts #{field}=#{val}" do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.send(method, "bool_#{val}", required_attrs.merge(field => val))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, resource_type.to_s, "bool_#{val}")
        expect(config[field.to_s]).to eq(val)
      end
    end
  end
end

# Type purity proof — proves ALL generated types inherit BaseAttributes,
# no T::Ref unions, refs handled at ResourceInput serialization boundary.
RSpec.shared_examples 'a pure typed provider' do |provider_module:, types_module:, lib_path:|
  describe 'type purity' do
    let(:types_files) { Dir.glob(File.join(lib_path, '**', 'types.rb')) }

    it 'has NO Dry::Struct inheritance (all types use BaseAttributes)' do
      violations = types_files.select { |f| File.read(f).include?('< Dry::Struct') }
      expect(violations).to be_empty,
        "#{violations.length} types still inherit Dry::Struct:\n#{violations.join("\n")}"
    end

    it 'has at least one BaseAttributes type' do
      base_types = types_files.select { |f| File.read(f).include?('< Pangea::Resources::BaseAttributes') }
      expect(base_types).not_to be_empty
    end

    it 'has NO T::Ref union types in generated code' do
      violations = types_files.select { |f| File.read(f).match?(/\| T::Ref\b/) }
      expect(violations).to be_empty,
        "#{violations.length} types contain | T::Ref unions:\n#{violations.join("\n")}"
    end
  end
end
