# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/github_actions_organization_secret/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GithubActionsOrganizationSecret
    include Pangea::Resources::ResourceBuilder

    define_resource :github_actions_organization_secret,
      attributes_class: Github::Types::ActionsOrganizationSecretAttributes,
      outputs: { id: :id },
      map: [:secret_name, :visibility],
      map_present: [:encrypted_value, :plaintext_value, :selected_repository_ids],
      map_bool: [:destroy_on_drift]
  end
  module Github
    include GithubActionsOrganizationSecret
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Github)
