# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# 
# Proves type purity across ALL generated types in this provider.
# Every type must inherit BaseAttributes. No T::Ref unions.
# Refs handled at ResourceInput serialization boundary.

require 'spec_helper'

RSpec.describe 'pangea-github type purity' do
  it_behaves_like 'a pure typed provider',
    provider_module: Pangea::Resources::Github,
    types_module: Pangea::Resources::Github::Types,
    lib_path: File.expand_path('../../lib', __dir__)
end
