# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/github_actions_repository_access_level/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GithubActionsRepositoryAccessLevel
    include Pangea::Resources::ResourceBuilder

    define_resource :github_actions_repository_access_level,
      attributes_class: Github::Types::ActionsRepositoryAccessLevelAttributes,
      outputs: { id: :id },
      map: [:access_level, :repository]
  end
  module Github
    include GithubActionsRepositoryAccessLevel
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Github)
