# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/github_repository_collaborators/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GithubRepositoryCollaborators
    include Pangea::Resources::ResourceBuilder

    define_resource :github_repository_collaborators,
      attributes_class: Github::Types::RepositoryCollaboratorsAttributes,
      outputs: { id: :id },
      map: [:repository],
      map_present: [:ignore_team, :team, :user]
  end
  module Github
    include GithubRepositoryCollaborators
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Github)
