# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Github::Types
  include Dry.Types()

  class RepositoryCollaboratorsAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Github::Types

    attribute :repository, T::String
    attribute? :ignore_team, T::Array.of(T::Hash).optional
    attribute? :team, T::Array.of(T::Hash).optional
    attribute? :user, T::Array.of(T::Hash).optional
  end
end
