# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/github_actions_repository_oidc_subject_claim_customization_template/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GithubActionsRepositoryOidcSubjectClaimCustomizationTemplate
    include Pangea::Resources::ResourceBuilder

    define_resource :github_actions_repository_oidc_subject_claim_customization_template,
      attributes_class: Github::Types::ActionsRepositoryOidcSubjectClaimCustomizationTemplateAttributes,
      outputs: { id: :id },
      map: [:repository],
      map_present: [:include_claim_keys],
      map_bool: [:use_default]
  end
  module Github
    include GithubActionsRepositoryOidcSubjectClaimCustomizationTemplate
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Github)
