# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Github::Types
  include Dry.Types()

  class ActionsRepositoryOidcSubjectClaimCustomizationTemplateAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Github::Types

    attribute :repository, T::String
    attribute :use_default, T::Bool
    attribute? :include_claim_keys, T::Array.of(T::String).optional
  end
end
