# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/github_actions_repository_permissions/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GithubActionsRepositoryPermissions
    include Pangea::Resources::ResourceBuilder

    define_resource :github_actions_repository_permissions,
      attributes_class: Github::Types::ActionsRepositoryPermissionsAttributes,
      outputs: { id: :id },
      map: [:repository],
      map_present: [:allowed_actions, :allowed_actions_config],
      map_bool: [:enabled, :sha_pinning_required]
  end
  module Github
    include GithubActionsRepositoryPermissions
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Github)
