# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Github::Types
  include Dry.Types()

  class ActionsRepositoryPermissionsAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Github::Types

    attribute :repository, T::String
    attribute? :allowed_actions, T::String.optional
    attribute? :allowed_actions_config, T::Hash.optional
    attribute? :enabled, T::Bool.optional
    attribute? :sha_pinning_required, T::Bool.optional
  end
end
