# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/github_organization_security_manager/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GithubOrganizationSecurityManager
    include Pangea::Resources::ResourceBuilder

    define_resource :github_organization_security_manager,
      attributes_class: Github::Types::OrganizationSecurityManagerAttributes,
      outputs: { id: :id },
      map: [:team_slug]
  end
  module Github
    include GithubOrganizationSecurityManager
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Github)
