# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Github::Types
  include Dry.Types()

  class RepositoryAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Github::Types

    attribute :name, T::String
    attribute? :allow_auto_merge, T::Bool.optional
    attribute? :allow_forking, T::Bool.optional
    attribute? :allow_merge_commit, T::Bool.optional
    attribute? :allow_rebase_merge, T::Bool.optional
    attribute? :allow_squash_merge, T::Bool.optional
    attribute? :allow_update_branch, T::Bool.optional
    attribute? :archive_on_destroy, T::Bool.optional
    attribute? :archived, T::Bool.optional
    attribute? :auto_init, T::Bool.optional
    attribute? :default_branch, T::String.optional
    attribute? :delete_branch_on_merge, T::Bool.optional
    attribute? :description, T::String.optional
    attribute? :etag, T::String.optional
    attribute? :fork, T::String.optional
    attribute? :gitignore_template, T::String.optional
    attribute? :has_discussions, T::Bool.optional
    attribute? :has_downloads, T::Bool.optional
    attribute? :has_issues, T::Bool.optional
    attribute? :has_projects, T::Bool.optional
    attribute? :has_wiki, T::Bool.optional
    attribute? :homepage_url, T::String.optional
    attribute? :ignore_vulnerability_alerts_during_read, T::Bool.optional
    attribute? :is_template, T::Bool.optional
    attribute? :license_template, T::String.optional
    attribute? :merge_commit_message, T::String.optional
    attribute? :merge_commit_title, T::String.optional
    attribute? :pages, T::Hash.optional
    attribute? :private, T::Bool.optional
    attribute? :security_and_analysis, T::Hash.optional
    attribute? :source_owner, T::String.optional
    attribute? :source_repo, T::String.optional
    attribute? :squash_merge_commit_message, T::String.optional
    attribute? :squash_merge_commit_title, T::String.optional
    attribute? :template, T::Hash.optional
    attribute? :topics, T::Array.of(T::String).optional
    attribute? :visibility, T::String.optional
    attribute? :vulnerability_alerts, T::Bool.optional
    attribute? :web_commit_signoff_required, T::Bool.optional
  end
end
