# Code generated by pangea-forge.
# InSpec profile for verifying github_actions_variable infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set GITHUB_TOKEN and GITHUB_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/github_actions_variable/ -t github://

control 'github_actions_variable-exists' do
  impact 1.0
  title 'Manages a github_actions_variable resource'
  desc 'Verify that the github_actions_variable resource exists and has expected properties'

  describe github_actions_variable(name: attribute('id')) do
    it { should exist }
    its('repository') { should_not be_nil }
    its('value') { should_not be_nil }
    its('variable_name') { should_not be_nil }
  end
end
