# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/github_membership/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GithubMembership
    include Pangea::Resources::ResourceBuilder

    define_resource :github_membership,
      attributes_class: Github::Types::MembershipAttributes,
      outputs: { id: :id },
      map: [:username],
      map_present: [:role],
      map_bool: [:downgrade_on_destroy]
  end
  module Github
    include GithubMembership
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Github)
