# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Github::Types
  include Dry.Types()

  class MembershipAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Github::Types

    attribute :username, T::String
    attribute? :downgrade_on_destroy, T::Bool.optional
    attribute? :role, T::String.optional
  end
end
