# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Github::Types
  include Dry.Types()

  class MembershipAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Github::Types

    attribute :username, T::String
    attribute? :downgrade_on_destroy, T::Bool.optional
    attribute? :role, T::String.optional
  end
end
