# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/github_team_repository/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GithubTeamRepository
    include Pangea::Resources::ResourceBuilder

    define_resource :github_team_repository,
      attributes_class: Github::Types::TeamRepositoryAttributes,
      outputs: { id: :id },
      map: [:repository, :team_id],
      map_present: [:permission]
  end
  module Github
    include GithubTeamRepository
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Github)
