# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/github_actions_organization_workflow_permissions/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GithubActionsOrganizationWorkflowPermissions
    include Pangea::Resources::ResourceBuilder

    define_resource :github_actions_organization_workflow_permissions,
      attributes_class: Github::Types::ActionsOrganizationWorkflowPermissionsAttributes,
      outputs: { id: :id },
      map: [:organization_slug],
      map_present: [:default_workflow_permissions],
      map_bool: [:can_approve_pull_request_reviews]
  end
  module Github
    include GithubActionsOrganizationWorkflowPermissions
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Github)
