# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Github::Types
  include Dry.Types()

  class ActionsOrganizationWorkflowPermissionsAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Github::Types

    attribute :organization_slug, T::String
    attribute? :can_approve_pull_request_reviews, T::Bool.optional
    attribute? :default_workflow_permissions, T::String.optional
  end
end
