# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/github_actions_organization_variable_repositories/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GithubActionsOrganizationVariableRepositories
    include Pangea::Resources::ResourceBuilder

    define_resource :github_actions_organization_variable_repositories,
      attributes_class: Github::Types::ActionsOrganizationVariableRepositoriesAttributes,
      outputs: { id: :id },
      map: [:selected_repository_ids, :variable_name]
  end
  module Github
    include GithubActionsOrganizationVariableRepositories
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Github)
