# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Github::Types
  include Dry.Types()

  class ActionsOrganizationVariableRepositoriesAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Github::Types

    attribute :selected_repository_ids, T::Array.of((T::Coercible::Integer | T::Coercible::Float))
    attribute :variable_name, T::String
  end
end
