# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/github_app_installation_repositories/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GithubAppInstallationRepositories
    include Pangea::Resources::ResourceBuilder

    define_resource :github_app_installation_repositories,
      attributes_class: Github::Types::AppInstallationRepositoriesAttributes,
      outputs: { id: :id },
      map: [:installation_id, :selected_repositories]
  end
  module Github
    include GithubAppInstallationRepositories
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Github)
