# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Github::Types
  include Dry.Types()

  class OrganizationRulesetAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Github::Types

    attribute :enforcement, T::String
    attribute :name, T::String
    attribute :rules, T::Array.of(T::Hash)
    attribute :target, T::String
    attribute? :bypass_actors, T::Array.of(T::Hash).optional
    attribute? :conditions, T::Array.of(T::Hash).optional
  end
end
