# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Github::Types
  include Dry.Types()

  class OrganizationRulesetAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Github::Types

    attribute :enforcement, T::String
    attribute :name, T::String
    attribute :rules, T::Hash
    attribute :target, T::String
    attribute? :bypass_actors, T::Array.of(T::Hash).optional
    attribute? :conditions, T::Hash.optional
  end
end
