# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/github_enterprise_organization/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GithubEnterpriseOrganization
    include Pangea::Resources::ResourceBuilder

    define_resource :github_enterprise_organization,
      attributes_class: Github::Types::EnterpriseOrganizationAttributes,
      outputs: { id: :id },
      map: [:admin_logins, :billing_email, :enterprise_id, :name],
      map_present: [:description, :display_name]
  end
  module Github
    include GithubEnterpriseOrganization
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Github)
