# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/github_dependabot_organization_secret_repositories/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GithubDependabotOrganizationSecretRepositories
    include Pangea::Resources::ResourceBuilder

    define_resource :github_dependabot_organization_secret_repositories,
      attributes_class: Github::Types::DependabotOrganizationSecretRepositoriesAttributes,
      outputs: { id: :id },
      map: [:secret_name, :selected_repository_ids]
  end
  module Github
    include GithubDependabotOrganizationSecretRepositories
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Github)
