# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/github_repository_collaborator/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GithubRepositoryCollaborator
    include Pangea::Resources::ResourceBuilder

    define_resource :github_repository_collaborator,
      attributes_class: Github::Types::RepositoryCollaboratorAttributes,
      outputs: { id: :id },
      map: [:repository, :username],
      map_present: [:permission],
      map_bool: [:permission_diff_suppression]
  end
  module Github
    include GithubRepositoryCollaborator
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Github)
