# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Github::Types
  include Dry.Types()

  class RepositoryCollaboratorAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Github::Types

    attribute :repository, T::String
    attribute :username, T::String
    attribute? :permission, T::String.optional
    attribute? :permission_diff_suppression, T::Bool.optional
  end
end
