# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/github_actions_hosted_runner/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GithubActionsHostedRunner
    include Pangea::Resources::ResourceBuilder

    define_resource :github_actions_hosted_runner,
      attributes_class: Github::Types::ActionsHostedRunnerAttributes,
      outputs: { id: :id },
      map: [:image, :name, :runner_group_id, :size],
      map_present: [:image_version, :maximum_runners],
      map_bool: [:image_gen, :public_ip_enabled]
  end
  module Github
    include GithubActionsHostedRunner
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Github)
