# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Github::Types
  include Dry.Types()

  class ActionsHostedRunnerAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Github::Types

    attribute :image, T::Array.of(T::Hash)
    attribute :name, T::String
    attribute :runner_group_id, T::Float
    attribute :size, T::String
    attribute? :image_gen, T::Bool.optional
    attribute? :image_version, T::String.optional
    attribute? :public_ip_enabled, T::Bool.optional
  end
end
