# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Github::Types
  include Dry.Types()

  class ActionsHostedRunnerAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Github::Types

    attribute :image, T::Hash
    attribute :name, T::String
    attribute :runner_group_id, (T::Coercible::Integer | T::Coercible::Float)
    attribute :size, T::String
    attribute? :image_gen, T::Bool.optional
    attribute? :image_version, T::String.optional
    attribute? :maximum_runners, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :public_ip_enabled, T::Bool.optional
  end
end
