# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/github_organization_block/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GithubOrganizationBlock
    include Pangea::Resources::ResourceBuilder

    define_resource :github_organization_block,
      attributes_class: Github::Types::OrganizationBlockAttributes,
      outputs: { id: :id },
      map: [:username]
  end
  module Github
    include GithubOrganizationBlock
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Github)
