# Code generated by pangea-forge.
# InSpec profile for verifying github_user_invitation_accepter infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set GITHUB_TOKEN and GITHUB_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/github_user_invitation_accepter/ -t github://

control 'github_user_invitation_accepter-exists' do
  impact 1.0
  title 'Manages a github_user_invitation_accepter resource'
  desc 'Verify that the github_user_invitation_accepter resource exists and has expected properties'

  describe github_user_invitation_accepter(name: attribute('id')) do
    it { should exist }
  end
end
