# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/github_repository_file/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GithubRepositoryFile
    include Pangea::Resources::ResourceBuilder

    define_resource :github_repository_file,
      attributes_class: Github::Types::RepositoryFileAttributes,
      outputs: { id: :id },
      map: [:content, :file, :repository],
      map_present: [:autocreate_branch_source_branch, :autocreate_branch_source_sha, :branch, :commit_author, :commit_email, :commit_message],
      map_bool: [:autocreate_branch, :overwrite_on_create]
  end
  module Github
    include GithubRepositoryFile
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Github)
