# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Github::Types
  include Dry.Types()

  class RepositoryFileAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Github::Types

    attribute :content, T::String
    attribute :file, T::String
    attribute :repository, T::String
    attribute? :autocreate_branch, T::Bool.optional
    attribute? :autocreate_branch_source_branch, T::String.optional
    attribute? :autocreate_branch_source_sha, T::String.optional
    attribute? :branch, T::String.optional
    attribute? :commit_author, T::String.optional
    attribute? :commit_email, T::String.optional
    attribute? :commit_message, T::String.optional
    attribute? :overwrite_on_create, T::Bool.optional
  end
end
