# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/github_team_membership/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GithubTeamMembership
    include Pangea::Resources::ResourceBuilder

    define_resource :github_team_membership,
      attributes_class: Github::Types::TeamMembershipAttributes,
      outputs: { id: :id },
      map: [:team_id, :username],
      map_present: [:role]
  end
  module Github
    include GithubTeamMembership
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Github)
