# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/github_enterprise_security_analysis_settings/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GithubEnterpriseSecurityAnalysisSettings
    include Pangea::Resources::ResourceBuilder

    define_resource :github_enterprise_security_analysis_settings,
      attributes_class: Github::Types::EnterpriseSecurityAnalysisSettingsAttributes,
      outputs: { id: :id },
      map: [:enterprise_slug],
      map_present: [:secret_scanning_push_protection_custom_link],
      map_bool: [:advanced_security_enabled_for_new_repositories, :secret_scanning_enabled_for_new_repositories, :secret_scanning_push_protection_enabled_for_new_repositories, :secret_scanning_validity_checks_enabled]
  end
  module Github
    include GithubEnterpriseSecurityAnalysisSettings
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Github)
