# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Github::Types
  include Dry.Types()

  class EnterpriseSecurityAnalysisSettingsAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Github::Types

    attribute :enterprise_slug, T::String
    attribute? :advanced_security_enabled_for_new_repositories, T::Bool.optional
    attribute? :secret_scanning_enabled_for_new_repositories, T::Bool.optional
    attribute? :secret_scanning_push_protection_custom_link, T::String.optional
    attribute? :secret_scanning_push_protection_enabled_for_new_repositories, T::Bool.optional
    attribute? :secret_scanning_validity_checks_enabled, T::Bool.optional
  end
end
