# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Github::Types
  include Dry.Types()

  class OrganizationRoleAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Github::Types

    attribute :name, T::String
    attribute :permissions, T::Array.of(T::String)
    attribute? :base_role, T::String.optional
    attribute? :description, T::String.optional
  end
end
