# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Github::Types
  include Dry.Types()

  class CodespacesSecretAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Github::Types

    attribute :repository, T::String
    attribute :secret_name, T::String
    attribute? :encrypted_value, T::String.optional
    attribute? :plaintext_value, T::String.optional
  end
end
