# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/github_release/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GithubRelease
    include Pangea::Resources::ResourceBuilder

    define_resource :github_release,
      attributes_class: Github::Types::ReleaseAttributes,
      outputs: { id: :id },
      map: [:repository, :tag_name],
      map_present: [:body, :discussion_category_name, :name, :target_commitish],
      map_bool: [:draft, :generate_release_notes, :prerelease]
  end
  module Github
    include GithubRelease
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Github)
