# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Github::Types
  include Dry.Types()

  class ReleaseAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Github::Types

    attribute :repository, T::String
    attribute :tag_name, T::String
    attribute? :body, T::String.optional
    attribute? :discussion_category_name, T::String.optional
    attribute? :draft, T::Bool.optional
    attribute? :generate_release_notes, T::Bool.optional
    attribute? :name, T::String.optional
    attribute? :prerelease, T::Bool.optional
    attribute? :target_commitish, T::String.optional
  end
end
