# Code generated by pangea-forge.
# InSpec profile for verifying github_enterprise_actions_permissions infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set GITHUB_TOKEN and GITHUB_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/github_enterprise_actions_permissions/ -t github://

control 'github_enterprise_actions_permissions-exists' do
  impact 1.0
  title 'Manages a github_enterprise_actions_permissions resource'
  desc 'Verify that the github_enterprise_actions_permissions resource exists and has expected properties'

  describe github_enterprise_actions_permissions(name: attribute('id')) do
    it { should exist }
    its('enabled_organizations') { should_not be_nil }
    its('enterprise_slug') { should_not be_nil }
  end
end
