# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/github_actions_environment_variable/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GithubActionsEnvironmentVariable
    include Pangea::Resources::ResourceBuilder

    define_resource :github_actions_environment_variable,
      attributes_class: Github::Types::ActionsEnvironmentVariableAttributes,
      outputs: { id: :id },
      map: [:environment, :repository, :value, :variable_name]
  end
  module Github
    include GithubActionsEnvironmentVariable
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Github)
