# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Github::Types
  include Dry.Types()

  class ActionsEnvironmentVariableAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Github::Types

    attribute :environment, T::String
    attribute :repository, T::String
    attribute :value, T::String
    attribute :variable_name, T::String
  end
end
