# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/github_actions_organization_secret_repositories/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GithubActionsOrganizationSecretRepositories
    include Pangea::Resources::ResourceBuilder

    define_resource :github_actions_organization_secret_repositories,
      attributes_class: Github::Types::ActionsOrganizationSecretRepositoriesAttributes,
      outputs: { id: :id },
      map: [:secret_name, :selected_repository_ids]
  end
  module Github
    include GithubActionsOrganizationSecretRepositories
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Github)
