# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/github_issue_label/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GithubIssueLabel
    include Pangea::Resources::ResourceBuilder

    define_resource :github_issue_label,
      attributes_class: Github::Types::IssueLabelAttributes,
      outputs: { id: :id },
      map: [:color, :name, :repository],
      map_present: [:description, :etag]
  end
  module Github
    include GithubIssueLabel
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Github)
