# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Github::Types
  include Dry.Types()

  class OrganizationRepositoryRoleAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Github::Types

    attribute :base_role, T::String
    attribute :name, T::String
    attribute :permissions, T::Array.of(T::String)
    attribute? :description, T::String.optional
  end
end
