# Code generated by pangea-forge.
# InSpec profile for verifying github_branch_protection_v3 infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set GITHUB_TOKEN and GITHUB_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/github_branch_protection_v3/ -t github://

control 'github_branch_protection_v3-exists' do
  impact 1.0
  title 'Manages a github_branch_protection_v3 resource'
  desc 'Verify that the github_branch_protection_v3 resource exists and has expected properties'

  describe github_branch_protection_v3(name: attribute('id')) do
    it { should exist }
    its('branch') { should_not be_nil }
    its('repository') { should_not be_nil }
  end
end
