# Code generated by pangea-forge.
# InSpec profile for verifying github_organization_role_team infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set GITHUB_TOKEN and GITHUB_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/github_organization_role_team/ -t github://

control 'github_organization_role_team-exists' do
  impact 1.0
  title 'Manages a github_organization_role_team resource'
  desc 'Verify that the github_organization_role_team resource exists and has expected properties'

  describe github_organization_role_team(name: attribute('id')) do
    it { should exist }
    its('role_id') { should_not be_nil }
    its('team_slug') { should_not be_nil }
  end
end
