# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Github::Types
  include Dry.Types()

  class RepositoryCustomPropertyAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Github::Types

    attribute :property_name, T::String
    attribute :property_type, T::String
    attribute :property_value, T::Array.of(T::String)
    attribute :repository, T::String
  end
end
