# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/github_organization_custom_role/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GithubOrganizationCustomRole
    include Pangea::Resources::ResourceBuilder

    define_resource :github_organization_custom_role,
      attributes_class: Github::Types::OrganizationCustomRoleAttributes,
      outputs: { id: :id },
      map: [:base_role, :name, :permissions],
      map_present: [:description]
  end
  module Github
    include GithubOrganizationCustomRole
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Github)
