# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a github_repository_autolink_reference resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GithubRepositoryAutolinkReference do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { key_prefix: 'test-value', repository: 'test-value', target_url_template: 'test-value' } }

  describe ':github_repository_autolink_reference' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_autolink_reference('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'github_repository_autolink_reference', 'test')
        validate_required_attributes(config, [:key_prefix, :repository, :target_url_template])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_repository_autolink_reference('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:github_repository_autolink_reference)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_repository_autolink_reference('test', required_attrs)

        expect(ref.id).to eq("${github_repository_autolink_reference.test.id}")
        expect(ref.etag).to eq("${github_repository_autolink_reference.test.etag}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_autolink_reference('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_repository_autolink_reference', 'test')
        expect(config).not_to have_key('etag')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ is_alphanumeric: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_autolink_reference('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_repository_autolink_reference', 'full')
        expect(config).to have_key('is_alphanumeric')
      end
    end

    context 'optional attributes' do
      it 'includes is_alphanumeric when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_autolink_reference('opt', required_attrs.merge(is_alphanumeric: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository_autolink_reference', 'opt')
        expect(config).to have_key('is_alphanumeric')
      end

      it 'omits is_alphanumeric when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_autolink_reference('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository_autolink_reference', 'minimal')
        expect(config).not_to have_key('is_alphanumeric')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts is_alphanumeric=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(is_alphanumeric: val)
          synth.github_repository_autolink_reference("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'github_repository_autolink_reference', "bool_#{val}")
          expect(config['is_alphanumeric']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_autolink_reference('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_repository_autolink_reference', 'typed')
        expect(config['key_prefix']).to be_a(String)
        expect(config['repository']).to be_a(String)
        expect(config['target_url_template']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_autolink_reference('first', required_attrs)
        synth.github_repository_autolink_reference('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'github_repository_autolink_reference')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :github_repository_autolink_reference,
    method: :github_repository_autolink_reference,
    required_attrs: { key_prefix: 'test-value', repository: 'test-value', target_url_template: 'test-value' },
    expected_outputs: [:id, :etag],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:is_alphanumeric]
end
