# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a github_repository_environment resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GithubRepositoryEnvironment do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { environment: 'test-value', repository: 'test-value' } }

  describe ':github_repository_environment' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_environment('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'github_repository_environment', 'test')
        validate_required_attributes(config, [:environment, :repository])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_repository_environment('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:github_repository_environment)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_repository_environment('test', required_attrs)

        expect(ref.id).to eq("${github_repository_environment.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ can_admins_bypass: true, deployment_branch_policy: { 'key1' => 'val1' }, prevent_self_review: true, reviewers: [{ 'key1' => 'val1' }], wait_timer: 3.14 }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_environment('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_repository_environment', 'full')
        expect(config).to have_key('can_admins_bypass')
        expect(config).to have_key('deployment_branch_policy')
        expect(config).to have_key('prevent_self_review')
        expect(config).to have_key('reviewers')
        expect(config).to have_key('wait_timer')
      end
    end

    context 'optional attributes' do
      it 'includes can_admins_bypass when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_environment('opt', required_attrs.merge(can_admins_bypass: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository_environment', 'opt')
        expect(config).to have_key('can_admins_bypass')
      end

      it 'omits can_admins_bypass when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_environment('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository_environment', 'minimal')
        expect(config).not_to have_key('can_admins_bypass')
      end
      it 'includes deployment_branch_policy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_environment('opt', required_attrs.merge(deployment_branch_policy: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository_environment', 'opt')
        expect(config).to have_key('deployment_branch_policy')
      end

      it 'omits deployment_branch_policy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_environment('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository_environment', 'minimal')
        expect(config).not_to have_key('deployment_branch_policy')
      end
      it 'includes prevent_self_review when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_environment('opt', required_attrs.merge(prevent_self_review: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository_environment', 'opt')
        expect(config).to have_key('prevent_self_review')
      end

      it 'omits prevent_self_review when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_environment('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository_environment', 'minimal')
        expect(config).not_to have_key('prevent_self_review')
      end
      it 'includes reviewers when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_environment('opt', required_attrs.merge(reviewers: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository_environment', 'opt')
        expect(config).to have_key('reviewers')
      end

      it 'omits reviewers when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_environment('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository_environment', 'minimal')
        expect(config).not_to have_key('reviewers')
      end
      it 'includes wait_timer when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_environment('opt', required_attrs.merge(wait_timer: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository_environment', 'opt')
        expect(config).to have_key('wait_timer')
      end

      it 'omits wait_timer when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_environment('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository_environment', 'minimal')
        expect(config).not_to have_key('wait_timer')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts can_admins_bypass=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(can_admins_bypass: val)
          synth.github_repository_environment("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'github_repository_environment', "bool_#{val}")
          expect(config['can_admins_bypass']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts prevent_self_review=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(prevent_self_review: val)
          synth.github_repository_environment("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'github_repository_environment', "bool_#{val}")
          expect(config['prevent_self_review']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_environment('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_repository_environment', 'typed')
        expect(config['environment']).to be_a(String)
        expect(config['repository']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_environment('first', required_attrs)
        synth.github_repository_environment('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'github_repository_environment')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :github_repository_environment,
    method: :github_repository_environment,
    required_attrs: { environment: 'test-value', repository: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:can_admins_bypass, :prevent_self_review]
end
