# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a github_repository_pull_request resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GithubRepositoryPullRequest do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { base_ref: 'test-value', base_repository: 'test-value', head_ref: 'test-value', title: 'test-value' } }

  describe ':github_repository_pull_request' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_pull_request('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'github_repository_pull_request', 'test')
        validate_required_attributes(config, [:base_ref, :base_repository, :head_ref, :title])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_repository_pull_request('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:github_repository_pull_request)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_repository_pull_request('test', required_attrs)

        expect(ref.id).to eq("${github_repository_pull_request.test.id}")
        expect(ref.base_sha).to eq("${github_repository_pull_request.test.base_sha}")
        expect(ref.draft).to eq("${github_repository_pull_request.test.draft}")
        expect(ref.head_sha).to eq("${github_repository_pull_request.test.head_sha}")
        expect(ref.labels).to eq("${github_repository_pull_request.test.labels}")
        expect(ref.number).to eq("${github_repository_pull_request.test.number}")
        expect(ref.opened_at).to eq("${github_repository_pull_request.test.opened_at}")
        expect(ref.opened_by).to eq("${github_repository_pull_request.test.opened_by}")
        expect(ref.state).to eq("${github_repository_pull_request.test.state}")
        expect(ref.updated_at).to eq("${github_repository_pull_request.test.updated_at}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_pull_request('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_repository_pull_request', 'test')
        expect(config).not_to have_key('base_sha')
        expect(config).not_to have_key('draft')
        expect(config).not_to have_key('head_sha')
        expect(config).not_to have_key('labels')
        expect(config).not_to have_key('number')
        expect(config).not_to have_key('opened_at')
        expect(config).not_to have_key('opened_by')
        expect(config).not_to have_key('state')
        expect(config).not_to have_key('updated_at')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ body: 'test-value', maintainer_can_modify: true, owner: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_pull_request('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_repository_pull_request', 'full')
        expect(config).to have_key('body')
        expect(config).to have_key('maintainer_can_modify')
        expect(config).to have_key('owner')
      end
    end

    context 'optional attributes' do
      it 'includes body when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_pull_request('opt', required_attrs.merge(body: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository_pull_request', 'opt')
        expect(config).to have_key('body')
      end

      it 'omits body when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_pull_request('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository_pull_request', 'minimal')
        expect(config).not_to have_key('body')
      end
      it 'includes maintainer_can_modify when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_pull_request('opt', required_attrs.merge(maintainer_can_modify: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository_pull_request', 'opt')
        expect(config).to have_key('maintainer_can_modify')
      end

      it 'omits maintainer_can_modify when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_pull_request('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository_pull_request', 'minimal')
        expect(config).not_to have_key('maintainer_can_modify')
      end
      it 'includes owner when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_pull_request('opt', required_attrs.merge(owner: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository_pull_request', 'opt')
        expect(config).to have_key('owner')
      end

      it 'omits owner when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_pull_request('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository_pull_request', 'minimal')
        expect(config).not_to have_key('owner')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts maintainer_can_modify=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(maintainer_can_modify: val)
          synth.github_repository_pull_request("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'github_repository_pull_request', "bool_#{val}")
          expect(config['maintainer_can_modify']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_pull_request('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_repository_pull_request', 'typed')
        expect(config['base_ref']).to be_a(String)
        expect(config['base_repository']).to be_a(String)
        expect(config['head_ref']).to be_a(String)
        expect(config['title']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_pull_request('first', required_attrs)
        synth.github_repository_pull_request('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'github_repository_pull_request')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :github_repository_pull_request,
    method: :github_repository_pull_request,
    required_attrs: { base_ref: 'test-value', base_repository: 'test-value', head_ref: 'test-value', title: 'test-value' },
    expected_outputs: [:id, :base_sha, :draft, :head_sha, :labels, :number, :opened_at, :opened_by, :state, :updated_at],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:maintainer_can_modify]
end
