# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a github_actions_organization_permissions resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GithubActionsOrganizationPermissions do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { enabled_repositories: 'test-value' } }

  describe ':github_actions_organization_permissions' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_actions_organization_permissions('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'github_actions_organization_permissions', 'test')
        validate_required_attributes(config, [:enabled_repositories])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_actions_organization_permissions('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:github_actions_organization_permissions)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_actions_organization_permissions('test', required_attrs)

        expect(ref.id).to eq("${github_actions_organization_permissions.test.id}")
        expect(ref.sha_pinning_required).to eq("${github_actions_organization_permissions.test.sha_pinning_required}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_actions_organization_permissions('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_actions_organization_permissions', 'test')
        expect(config).not_to have_key('sha_pinning_required')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ allowed_actions: 'test-value', allowed_actions_config: [{ 'key1' => 'val1' }], enabled_repositories_config: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_actions_organization_permissions('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_actions_organization_permissions', 'full')
        expect(config).to have_key('allowed_actions')
        expect(config).to have_key('allowed_actions_config')
        expect(config).to have_key('enabled_repositories_config')
      end
    end

    context 'optional attributes' do
      it 'includes allowed_actions when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_actions_organization_permissions('opt', required_attrs.merge(allowed_actions: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_actions_organization_permissions', 'opt')
        expect(config).to have_key('allowed_actions')
      end

      it 'omits allowed_actions when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_actions_organization_permissions('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_actions_organization_permissions', 'minimal')
        expect(config).not_to have_key('allowed_actions')
      end
      it 'includes allowed_actions_config when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_actions_organization_permissions('opt', required_attrs.merge(allowed_actions_config: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_actions_organization_permissions', 'opt')
        expect(config).to have_key('allowed_actions_config')
      end

      it 'omits allowed_actions_config when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_actions_organization_permissions('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_actions_organization_permissions', 'minimal')
        expect(config).not_to have_key('allowed_actions_config')
      end
      it 'includes enabled_repositories_config when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_actions_organization_permissions('opt', required_attrs.merge(enabled_repositories_config: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_actions_organization_permissions', 'opt')
        expect(config).to have_key('enabled_repositories_config')
      end

      it 'omits enabled_repositories_config when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_actions_organization_permissions('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_actions_organization_permissions', 'minimal')
        expect(config).not_to have_key('enabled_repositories_config')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_actions_organization_permissions('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_actions_organization_permissions', 'typed')
        expect(config['enabled_repositories']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_actions_organization_permissions('first', required_attrs)
        synth.github_actions_organization_permissions('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'github_actions_organization_permissions')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :github_actions_organization_permissions,
    method: :github_actions_organization_permissions,
    required_attrs: { enabled_repositories: 'test-value' },
    expected_outputs: [:id, :sha_pinning_required],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
