# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a github_actions_organization_secret resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GithubActionsOrganizationSecret do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { secret_name: 'test-value', visibility: 'test-value' } }

  describe ':github_actions_organization_secret' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_actions_organization_secret('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'github_actions_organization_secret', 'test')
        validate_required_attributes(config, [:secret_name, :visibility])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_actions_organization_secret('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:github_actions_organization_secret)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_actions_organization_secret('test', required_attrs)

        expect(ref.id).to eq("${github_actions_organization_secret.test.id}")
        expect(ref.created_at).to eq("${github_actions_organization_secret.test.created_at}")
        expect(ref.key_id).to eq("${github_actions_organization_secret.test.key_id}")
        expect(ref.remote_updated_at).to eq("${github_actions_organization_secret.test.remote_updated_at}")
        expect(ref.updated_at).to eq("${github_actions_organization_secret.test.updated_at}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_actions_organization_secret('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_actions_organization_secret', 'test')
        expect(config).not_to have_key('created_at')
        expect(config).not_to have_key('key_id')
        expect(config).not_to have_key('remote_updated_at')
        expect(config).not_to have_key('updated_at')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ destroy_on_drift: true, encrypted_value: 'test-value', plaintext_value: 'test-value', selected_repository_ids: [3.14] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_actions_organization_secret('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_actions_organization_secret', 'full')
        expect(config).to have_key('destroy_on_drift')
        expect(config).to have_key('encrypted_value')
        expect(config).to have_key('plaintext_value')
        expect(config).to have_key('selected_repository_ids')
      end
    end

    context 'optional attributes' do
      it 'includes destroy_on_drift when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_actions_organization_secret('opt', required_attrs.merge(destroy_on_drift: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_actions_organization_secret', 'opt')
        expect(config).to have_key('destroy_on_drift')
      end

      it 'omits destroy_on_drift when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_actions_organization_secret('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_actions_organization_secret', 'minimal')
        expect(config).not_to have_key('destroy_on_drift')
      end
      it 'includes encrypted_value when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_actions_organization_secret('opt', required_attrs.merge(encrypted_value: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_actions_organization_secret', 'opt')
        expect(config).to have_key('encrypted_value')
      end

      it 'omits encrypted_value when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_actions_organization_secret('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_actions_organization_secret', 'minimal')
        expect(config).not_to have_key('encrypted_value')
      end
      it 'includes plaintext_value when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_actions_organization_secret('opt', required_attrs.merge(plaintext_value: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_actions_organization_secret', 'opt')
        expect(config).to have_key('plaintext_value')
      end

      it 'omits plaintext_value when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_actions_organization_secret('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_actions_organization_secret', 'minimal')
        expect(config).not_to have_key('plaintext_value')
      end
      it 'includes selected_repository_ids when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_actions_organization_secret('opt', required_attrs.merge(selected_repository_ids: [3.14]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_actions_organization_secret', 'opt')
        expect(config).to have_key('selected_repository_ids')
      end

      it 'omits selected_repository_ids when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_actions_organization_secret('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_actions_organization_secret', 'minimal')
        expect(config).not_to have_key('selected_repository_ids')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:encrypted_value, :plaintext_value]
        expect(sensitive_fields).to include(:encrypted_value)
        expect(sensitive_fields).to include(:plaintext_value)
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts destroy_on_drift=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(destroy_on_drift: val)
          synth.github_actions_organization_secret("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'github_actions_organization_secret', "bool_#{val}")
          expect(config['destroy_on_drift']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_actions_organization_secret('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_actions_organization_secret', 'typed')
        expect(config['secret_name']).to be_a(String)
        expect(config['visibility']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_actions_organization_secret('first', required_attrs)
        synth.github_actions_organization_secret('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'github_actions_organization_secret')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :github_actions_organization_secret,
    method: :github_actions_organization_secret,
    required_attrs: { secret_name: 'test-value', visibility: 'test-value' },
    expected_outputs: [:id, :created_at, :key_id, :remote_updated_at, :updated_at],
    sensitive_fields: [:encrypted_value, :plaintext_value],
    immutable_fields: [],
    boolean_fields: [:destroy_on_drift]
end
