# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a github_team_settings resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GithubTeamSettings do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { team_id: 'test-value' } }

  describe ':github_team_settings' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_team_settings('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'github_team_settings', 'test')
        validate_required_attributes(config, [:team_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_team_settings('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:github_team_settings)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_team_settings('test', required_attrs)

        expect(ref.id).to eq("${github_team_settings.test.id}")
        expect(ref.team_slug).to eq("${github_team_settings.test.team_slug}")
        expect(ref.team_uid).to eq("${github_team_settings.test.team_uid}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_team_settings('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_team_settings', 'test')
        expect(config).not_to have_key('team_slug')
        expect(config).not_to have_key('team_uid')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ review_request_delegation: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_team_settings('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_team_settings', 'full')
        expect(config).to have_key('review_request_delegation')
      end
    end

    context 'optional attributes' do
      it 'includes review_request_delegation when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_team_settings('opt', required_attrs.merge(review_request_delegation: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_team_settings', 'opt')
        expect(config).to have_key('review_request_delegation')
      end

      it 'omits review_request_delegation when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_team_settings('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_team_settings', 'minimal')
        expect(config).not_to have_key('review_request_delegation')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_team_settings('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_team_settings', 'typed')
        expect(config['team_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_team_settings('first', required_attrs)
        synth.github_team_settings('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'github_team_settings')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :github_team_settings,
    method: :github_team_settings,
    required_attrs: { team_id: 'test-value' },
    expected_outputs: [:id, :team_slug, :team_uid],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
