# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a github_actions_repository_access_level resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GithubActionsRepositoryAccessLevel do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { access_level: 'test-value', repository: 'test-value' } }

  describe ':github_actions_repository_access_level' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_actions_repository_access_level('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'github_actions_repository_access_level', 'test')
        validate_required_attributes(config, [:access_level, :repository])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_actions_repository_access_level('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:github_actions_repository_access_level)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_actions_repository_access_level('test', required_attrs)

        expect(ref.id).to eq("${github_actions_repository_access_level.test.id}")
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_actions_repository_access_level('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_actions_repository_access_level', 'typed')
        expect(config['access_level']).to be_a(String)
        expect(config['repository']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_actions_repository_access_level('first', required_attrs)
        synth.github_actions_repository_access_level('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'github_actions_repository_access_level')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :github_actions_repository_access_level,
    method: :github_actions_repository_access_level,
    required_attrs: { access_level: 'test-value', repository: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
