# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a github_organization_ruleset resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GithubOrganizationRuleset do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { enforcement: 'test-value', name: 'test-value', rules: [{ 'key1' => 'val1' }], target: 'test-value' } }

  describe ':github_organization_ruleset' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_organization_ruleset('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'github_organization_ruleset', 'test')
        validate_required_attributes(config, [:enforcement, :name, :rules, :target])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_organization_ruleset('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:github_organization_ruleset)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_organization_ruleset('test', required_attrs)

        expect(ref.id).to eq("${github_organization_ruleset.test.id}")
        expect(ref.etag).to eq("${github_organization_ruleset.test.etag}")
        expect(ref.node_id).to eq("${github_organization_ruleset.test.node_id}")
        expect(ref.ruleset_id).to eq("${github_organization_ruleset.test.ruleset_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_organization_ruleset('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_organization_ruleset', 'test')
        expect(config).not_to have_key('etag')
        expect(config).not_to have_key('node_id')
        expect(config).not_to have_key('ruleset_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ bypass_actors: [{ 'key1' => 'val1' }], conditions: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_organization_ruleset('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_organization_ruleset', 'full')
        expect(config).to have_key('bypass_actors')
        expect(config).to have_key('conditions')
      end
    end

    context 'optional attributes' do
      it 'includes bypass_actors when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_organization_ruleset('opt', required_attrs.merge(bypass_actors: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_organization_ruleset', 'opt')
        expect(config).to have_key('bypass_actors')
      end

      it 'omits bypass_actors when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_organization_ruleset('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_organization_ruleset', 'minimal')
        expect(config).not_to have_key('bypass_actors')
      end
      it 'includes conditions when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_organization_ruleset('opt', required_attrs.merge(conditions: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_organization_ruleset', 'opt')
        expect(config).to have_key('conditions')
      end

      it 'omits conditions when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_organization_ruleset('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_organization_ruleset', 'minimal')
        expect(config).not_to have_key('conditions')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_organization_ruleset('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_organization_ruleset', 'typed')
        expect(config['enforcement']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['rules']).to be_a(Array)
        expect(config['target']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_organization_ruleset('first', required_attrs)
        synth.github_organization_ruleset('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'github_organization_ruleset')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :github_organization_ruleset,
    method: :github_organization_ruleset,
    required_attrs: { enforcement: 'test-value', name: 'test-value', rules: [{ 'key1' => 'val1' }], target: 'test-value' },
    expected_outputs: [:id, :etag, :node_id, :ruleset_id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
