# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a github_team_sync_group_mapping resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GithubTeamSyncGroupMapping do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { team_slug: 'test-value' } }

  describe ':github_team_sync_group_mapping' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_team_sync_group_mapping('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'github_team_sync_group_mapping', 'test')
        validate_required_attributes(config, [:team_slug])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_team_sync_group_mapping('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:github_team_sync_group_mapping)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_team_sync_group_mapping('test', required_attrs)

        expect(ref.id).to eq("${github_team_sync_group_mapping.test.id}")
        expect(ref.etag).to eq("${github_team_sync_group_mapping.test.etag}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_team_sync_group_mapping('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_team_sync_group_mapping', 'test')
        expect(config).not_to have_key('etag')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ group: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_team_sync_group_mapping('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_team_sync_group_mapping', 'full')
        expect(config).to have_key('group')
      end
    end

    context 'optional attributes' do
      it 'includes group when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_team_sync_group_mapping('opt', required_attrs.merge(group: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_team_sync_group_mapping', 'opt')
        expect(config).to have_key('group')
      end

      it 'omits group when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_team_sync_group_mapping('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_team_sync_group_mapping', 'minimal')
        expect(config).not_to have_key('group')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_team_sync_group_mapping('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_team_sync_group_mapping', 'typed')
        expect(config['team_slug']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_team_sync_group_mapping('first', required_attrs)
        synth.github_team_sync_group_mapping('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'github_team_sync_group_mapping')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :github_team_sync_group_mapping,
    method: :github_team_sync_group_mapping,
    required_attrs: { team_slug: 'test-value' },
    expected_outputs: [:id, :etag],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
