# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a github_organization_custom_properties resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GithubOrganizationCustomProperties do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { property_name: 'test-value' } }

  describe ':github_organization_custom_properties' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_organization_custom_properties('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'github_organization_custom_properties', 'test')
        validate_required_attributes(config, [:property_name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_organization_custom_properties('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:github_organization_custom_properties)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_organization_custom_properties('test', required_attrs)

        expect(ref.id).to eq("${github_organization_custom_properties.test.id}")
        expect(ref.allowed_values).to eq("${github_organization_custom_properties.test.allowed_values}")
        expect(ref.default_value).to eq("${github_organization_custom_properties.test.default_value}")
        expect(ref.description).to eq("${github_organization_custom_properties.test.description}")
        expect(ref.values_editable_by).to eq("${github_organization_custom_properties.test.values_editable_by}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_organization_custom_properties('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_organization_custom_properties', 'test')
        expect(config).not_to have_key('allowed_values')
        expect(config).not_to have_key('default_value')
        expect(config).not_to have_key('description')
        expect(config).not_to have_key('values_editable_by')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ allowed_values: ['test-value'], default_value: 'test-value', description: 'test-value', required: true, value_type: 'test-value', values_editable_by: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_organization_custom_properties('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_organization_custom_properties', 'full')
        expect(config).to have_key('allowed_values')
        expect(config).to have_key('default_value')
        expect(config).to have_key('description')
        expect(config).to have_key('required')
        expect(config).to have_key('value_type')
        expect(config).to have_key('values_editable_by')
      end
    end

    context 'optional attributes' do
      it 'includes allowed_values when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_organization_custom_properties('opt', required_attrs.merge(allowed_values: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_organization_custom_properties', 'opt')
        expect(config).to have_key('allowed_values')
      end

      it 'omits allowed_values when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_organization_custom_properties('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_organization_custom_properties', 'minimal')
        expect(config).not_to have_key('allowed_values')
      end
      it 'includes default_value when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_organization_custom_properties('opt', required_attrs.merge(default_value: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_organization_custom_properties', 'opt')
        expect(config).to have_key('default_value')
      end

      it 'omits default_value when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_organization_custom_properties('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_organization_custom_properties', 'minimal')
        expect(config).not_to have_key('default_value')
      end
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_organization_custom_properties('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_organization_custom_properties', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_organization_custom_properties('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_organization_custom_properties', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes required when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_organization_custom_properties('opt', required_attrs.merge(required: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_organization_custom_properties', 'opt')
        expect(config).to have_key('required')
      end

      it 'omits required when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_organization_custom_properties('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_organization_custom_properties', 'minimal')
        expect(config).not_to have_key('required')
      end
      it 'includes value_type when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_organization_custom_properties('opt', required_attrs.merge(value_type: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_organization_custom_properties', 'opt')
        expect(config).to have_key('value_type')
      end

      it 'omits value_type when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_organization_custom_properties('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_organization_custom_properties', 'minimal')
        expect(config).not_to have_key('value_type')
      end
      it 'includes values_editable_by when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_organization_custom_properties('opt', required_attrs.merge(values_editable_by: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_organization_custom_properties', 'opt')
        expect(config).to have_key('values_editable_by')
      end

      it 'omits values_editable_by when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_organization_custom_properties('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_organization_custom_properties', 'minimal')
        expect(config).not_to have_key('values_editable_by')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts required=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(required: val)
          synth.github_organization_custom_properties("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'github_organization_custom_properties', "bool_#{val}")
          expect(config['required']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_organization_custom_properties('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_organization_custom_properties', 'typed')
        expect(config['property_name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_organization_custom_properties('first', required_attrs)
        synth.github_organization_custom_properties('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'github_organization_custom_properties')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :github_organization_custom_properties,
    method: :github_organization_custom_properties,
    required_attrs: { property_name: 'test-value' },
    expected_outputs: [:id, :allowed_values, :default_value, :description, :values_editable_by],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:required]
end
