# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a github_enterprise_organization resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GithubEnterpriseOrganization do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { admin_logins: ['test-value'], billing_email: 'test-value', enterprise_id: 'test-value', name: 'test-value' } }

  describe ':github_enterprise_organization' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_enterprise_organization('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'github_enterprise_organization', 'test')
        validate_required_attributes(config, [:admin_logins, :billing_email, :enterprise_id, :name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_enterprise_organization('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:github_enterprise_organization)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_enterprise_organization('test', required_attrs)

        expect(ref.id).to eq("${github_enterprise_organization.test.id}")
        expect(ref.database_id).to eq("${github_enterprise_organization.test.database_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_enterprise_organization('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_enterprise_organization', 'test')
        expect(config).not_to have_key('database_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ description: 'test-value', display_name: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_enterprise_organization('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_enterprise_organization', 'full')
        expect(config).to have_key('description')
        expect(config).to have_key('display_name')
      end
    end

    context 'optional attributes' do
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_enterprise_organization('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_enterprise_organization', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_enterprise_organization('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_enterprise_organization', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes display_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_enterprise_organization('opt', required_attrs.merge(display_name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_enterprise_organization', 'opt')
        expect(config).to have_key('display_name')
      end

      it 'omits display_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_enterprise_organization('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_enterprise_organization', 'minimal')
        expect(config).not_to have_key('display_name')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_enterprise_organization('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_enterprise_organization', 'typed')
        expect(config['admin_logins']).to be_a(Array)
        expect(config['billing_email']).to be_a(String)
        expect(config['enterprise_id']).to be_a(String)
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_enterprise_organization('first', required_attrs)
        synth.github_enterprise_organization('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'github_enterprise_organization')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :github_enterprise_organization,
    method: :github_enterprise_organization,
    required_attrs: { admin_logins: ['test-value'], billing_email: 'test-value', enterprise_id: 'test-value', name: 'test-value' },
    expected_outputs: [:id, :database_id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
