# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a github_repository resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GithubRepository do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':github_repository' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'github_repository', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_repository('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:github_repository)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_repository('test', required_attrs)

        expect(ref.id).to eq("${github_repository.test.id}")
        expect(ref.allow_forking).to eq("${github_repository.test.allow_forking}")
        expect(ref.default_branch).to eq("${github_repository.test.default_branch}")
        expect(ref.etag).to eq("${github_repository.test.etag}")
        expect(ref.fork).to eq("${github_repository.test.fork}")
        expect(ref.full_name).to eq("${github_repository.test.full_name}")
        expect(ref.git_clone_url).to eq("${github_repository.test.git_clone_url}")
        expect(ref.html_url).to eq("${github_repository.test.html_url}")
        expect(ref.http_clone_url).to eq("${github_repository.test.http_clone_url}")
        expect(ref.node_id).to eq("${github_repository.test.node_id}")
        expect(ref.primary_language).to eq("${github_repository.test.primary_language}")
        expect(ref.private).to eq("${github_repository.test.private}")
        expect(ref.repo_id).to eq("${github_repository.test.repo_id}")
        expect(ref.source_owner).to eq("${github_repository.test.source_owner}")
        expect(ref.source_repo).to eq("${github_repository.test.source_repo}")
        expect(ref.ssh_clone_url).to eq("${github_repository.test.ssh_clone_url}")
        expect(ref.svn_url).to eq("${github_repository.test.svn_url}")
        expect(ref.topics).to eq("${github_repository.test.topics}")
        expect(ref.visibility).to eq("${github_repository.test.visibility}")
        expect(ref.vulnerability_alerts).to eq("${github_repository.test.vulnerability_alerts}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_repository', 'test')
        expect(config).not_to have_key('allow_forking')
        expect(config).not_to have_key('default_branch')
        expect(config).not_to have_key('etag')
        expect(config).not_to have_key('fork')
        expect(config).not_to have_key('full_name')
        expect(config).not_to have_key('git_clone_url')
        expect(config).not_to have_key('html_url')
        expect(config).not_to have_key('http_clone_url')
        expect(config).not_to have_key('node_id')
        expect(config).not_to have_key('primary_language')
        expect(config).not_to have_key('private')
        expect(config).not_to have_key('repo_id')
        expect(config).not_to have_key('source_owner')
        expect(config).not_to have_key('source_repo')
        expect(config).not_to have_key('ssh_clone_url')
        expect(config).not_to have_key('svn_url')
        expect(config).not_to have_key('topics')
        expect(config).not_to have_key('visibility')
        expect(config).not_to have_key('vulnerability_alerts')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ allow_auto_merge: true, allow_merge_commit: true, allow_rebase_merge: true, allow_squash_merge: true, allow_update_branch: true, archive_on_destroy: true, archived: true, auto_init: true, delete_branch_on_merge: true, description: 'test-value', gitignore_template: 'test-value', has_discussions: true, has_downloads: true, has_issues: true, has_projects: true, has_wiki: true, homepage_url: 'test-value', ignore_vulnerability_alerts_during_read: true, is_template: true, license_template: 'test-value', merge_commit_message: 'test-value', merge_commit_title: 'test-value', pages: [{ 'key1' => 'val1' }], security_and_analysis: [{ 'key1' => 'val1' }], squash_merge_commit_message: 'test-value', squash_merge_commit_title: 'test-value', template: [{ 'key1' => 'val1' }], web_commit_signoff_required: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_repository', 'full')
        expect(config).to have_key('allow_auto_merge')
        expect(config).to have_key('allow_merge_commit')
        expect(config).to have_key('allow_rebase_merge')
        expect(config).to have_key('allow_squash_merge')
        expect(config).to have_key('allow_update_branch')
        expect(config).to have_key('archive_on_destroy')
        expect(config).to have_key('archived')
        expect(config).to have_key('auto_init')
        expect(config).to have_key('delete_branch_on_merge')
        expect(config).to have_key('description')
        expect(config).to have_key('gitignore_template')
        expect(config).to have_key('has_discussions')
        expect(config).to have_key('has_downloads')
        expect(config).to have_key('has_issues')
        expect(config).to have_key('has_projects')
        expect(config).to have_key('has_wiki')
        expect(config).to have_key('homepage_url')
        expect(config).to have_key('ignore_vulnerability_alerts_during_read')
        expect(config).to have_key('is_template')
        expect(config).to have_key('license_template')
        expect(config).to have_key('merge_commit_message')
        expect(config).to have_key('merge_commit_title')
        expect(config).to have_key('pages')
        expect(config).to have_key('security_and_analysis')
        expect(config).to have_key('squash_merge_commit_message')
        expect(config).to have_key('squash_merge_commit_title')
        expect(config).to have_key('template')
        expect(config).to have_key('web_commit_signoff_required')
      end
    end

    context 'optional attributes' do
      it 'includes allow_auto_merge when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('opt', required_attrs.merge(allow_auto_merge: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository', 'opt')
        expect(config).to have_key('allow_auto_merge')
      end

      it 'omits allow_auto_merge when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository', 'minimal')
        expect(config).not_to have_key('allow_auto_merge')
      end
      it 'includes allow_merge_commit when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('opt', required_attrs.merge(allow_merge_commit: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository', 'opt')
        expect(config).to have_key('allow_merge_commit')
      end

      it 'omits allow_merge_commit when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository', 'minimal')
        expect(config).not_to have_key('allow_merge_commit')
      end
      it 'includes allow_rebase_merge when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('opt', required_attrs.merge(allow_rebase_merge: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository', 'opt')
        expect(config).to have_key('allow_rebase_merge')
      end

      it 'omits allow_rebase_merge when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository', 'minimal')
        expect(config).not_to have_key('allow_rebase_merge')
      end
      it 'includes allow_squash_merge when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('opt', required_attrs.merge(allow_squash_merge: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository', 'opt')
        expect(config).to have_key('allow_squash_merge')
      end

      it 'omits allow_squash_merge when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository', 'minimal')
        expect(config).not_to have_key('allow_squash_merge')
      end
      it 'includes allow_update_branch when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('opt', required_attrs.merge(allow_update_branch: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository', 'opt')
        expect(config).to have_key('allow_update_branch')
      end

      it 'omits allow_update_branch when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository', 'minimal')
        expect(config).not_to have_key('allow_update_branch')
      end
      it 'includes archive_on_destroy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('opt', required_attrs.merge(archive_on_destroy: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository', 'opt')
        expect(config).to have_key('archive_on_destroy')
      end

      it 'omits archive_on_destroy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository', 'minimal')
        expect(config).not_to have_key('archive_on_destroy')
      end
      it 'includes archived when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('opt', required_attrs.merge(archived: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository', 'opt')
        expect(config).to have_key('archived')
      end

      it 'omits archived when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository', 'minimal')
        expect(config).not_to have_key('archived')
      end
      it 'includes auto_init when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('opt', required_attrs.merge(auto_init: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository', 'opt')
        expect(config).to have_key('auto_init')
      end

      it 'omits auto_init when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository', 'minimal')
        expect(config).not_to have_key('auto_init')
      end
      it 'includes delete_branch_on_merge when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('opt', required_attrs.merge(delete_branch_on_merge: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository', 'opt')
        expect(config).to have_key('delete_branch_on_merge')
      end

      it 'omits delete_branch_on_merge when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository', 'minimal')
        expect(config).not_to have_key('delete_branch_on_merge')
      end
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes gitignore_template when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('opt', required_attrs.merge(gitignore_template: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository', 'opt')
        expect(config).to have_key('gitignore_template')
      end

      it 'omits gitignore_template when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository', 'minimal')
        expect(config).not_to have_key('gitignore_template')
      end
      it 'includes has_discussions when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('opt', required_attrs.merge(has_discussions: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository', 'opt')
        expect(config).to have_key('has_discussions')
      end

      it 'omits has_discussions when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository', 'minimal')
        expect(config).not_to have_key('has_discussions')
      end
      it 'includes has_downloads when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('opt', required_attrs.merge(has_downloads: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository', 'opt')
        expect(config).to have_key('has_downloads')
      end

      it 'omits has_downloads when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository', 'minimal')
        expect(config).not_to have_key('has_downloads')
      end
      it 'includes has_issues when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('opt', required_attrs.merge(has_issues: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository', 'opt')
        expect(config).to have_key('has_issues')
      end

      it 'omits has_issues when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository', 'minimal')
        expect(config).not_to have_key('has_issues')
      end
      it 'includes has_projects when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('opt', required_attrs.merge(has_projects: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository', 'opt')
        expect(config).to have_key('has_projects')
      end

      it 'omits has_projects when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository', 'minimal')
        expect(config).not_to have_key('has_projects')
      end
      it 'includes has_wiki when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('opt', required_attrs.merge(has_wiki: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository', 'opt')
        expect(config).to have_key('has_wiki')
      end

      it 'omits has_wiki when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository', 'minimal')
        expect(config).not_to have_key('has_wiki')
      end
      it 'includes homepage_url when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('opt', required_attrs.merge(homepage_url: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository', 'opt')
        expect(config).to have_key('homepage_url')
      end

      it 'omits homepage_url when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository', 'minimal')
        expect(config).not_to have_key('homepage_url')
      end
      it 'includes ignore_vulnerability_alerts_during_read when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('opt', required_attrs.merge(ignore_vulnerability_alerts_during_read: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository', 'opt')
        expect(config).to have_key('ignore_vulnerability_alerts_during_read')
      end

      it 'omits ignore_vulnerability_alerts_during_read when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository', 'minimal')
        expect(config).not_to have_key('ignore_vulnerability_alerts_during_read')
      end
      it 'includes is_template when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('opt', required_attrs.merge(is_template: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository', 'opt')
        expect(config).to have_key('is_template')
      end

      it 'omits is_template when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository', 'minimal')
        expect(config).not_to have_key('is_template')
      end
      it 'includes license_template when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('opt', required_attrs.merge(license_template: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository', 'opt')
        expect(config).to have_key('license_template')
      end

      it 'omits license_template when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository', 'minimal')
        expect(config).not_to have_key('license_template')
      end
      it 'includes merge_commit_message when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('opt', required_attrs.merge(merge_commit_message: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository', 'opt')
        expect(config).to have_key('merge_commit_message')
      end

      it 'omits merge_commit_message when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository', 'minimal')
        expect(config).not_to have_key('merge_commit_message')
      end
      it 'includes merge_commit_title when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('opt', required_attrs.merge(merge_commit_title: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository', 'opt')
        expect(config).to have_key('merge_commit_title')
      end

      it 'omits merge_commit_title when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository', 'minimal')
        expect(config).not_to have_key('merge_commit_title')
      end
      it 'includes pages when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('opt', required_attrs.merge(pages: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository', 'opt')
        expect(config).to have_key('pages')
      end

      it 'omits pages when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository', 'minimal')
        expect(config).not_to have_key('pages')
      end
      it 'includes security_and_analysis when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('opt', required_attrs.merge(security_and_analysis: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository', 'opt')
        expect(config).to have_key('security_and_analysis')
      end

      it 'omits security_and_analysis when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository', 'minimal')
        expect(config).not_to have_key('security_and_analysis')
      end
      it 'includes squash_merge_commit_message when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('opt', required_attrs.merge(squash_merge_commit_message: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository', 'opt')
        expect(config).to have_key('squash_merge_commit_message')
      end

      it 'omits squash_merge_commit_message when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository', 'minimal')
        expect(config).not_to have_key('squash_merge_commit_message')
      end
      it 'includes squash_merge_commit_title when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('opt', required_attrs.merge(squash_merge_commit_title: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository', 'opt')
        expect(config).to have_key('squash_merge_commit_title')
      end

      it 'omits squash_merge_commit_title when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository', 'minimal')
        expect(config).not_to have_key('squash_merge_commit_title')
      end
      it 'includes template when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('opt', required_attrs.merge(template: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository', 'opt')
        expect(config).to have_key('template')
      end

      it 'omits template when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository', 'minimal')
        expect(config).not_to have_key('template')
      end
      it 'includes web_commit_signoff_required when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('opt', required_attrs.merge(web_commit_signoff_required: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository', 'opt')
        expect(config).to have_key('web_commit_signoff_required')
      end

      it 'omits web_commit_signoff_required when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository', 'minimal')
        expect(config).not_to have_key('web_commit_signoff_required')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts allow_auto_merge=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(allow_auto_merge: val)
          synth.github_repository("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'github_repository', "bool_#{val}")
          expect(config['allow_auto_merge']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts allow_merge_commit=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(allow_merge_commit: val)
          synth.github_repository("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'github_repository', "bool_#{val}")
          expect(config['allow_merge_commit']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts allow_rebase_merge=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(allow_rebase_merge: val)
          synth.github_repository("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'github_repository', "bool_#{val}")
          expect(config['allow_rebase_merge']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts allow_squash_merge=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(allow_squash_merge: val)
          synth.github_repository("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'github_repository', "bool_#{val}")
          expect(config['allow_squash_merge']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts allow_update_branch=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(allow_update_branch: val)
          synth.github_repository("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'github_repository', "bool_#{val}")
          expect(config['allow_update_branch']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts archive_on_destroy=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(archive_on_destroy: val)
          synth.github_repository("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'github_repository', "bool_#{val}")
          expect(config['archive_on_destroy']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts archived=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(archived: val)
          synth.github_repository("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'github_repository', "bool_#{val}")
          expect(config['archived']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts auto_init=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(auto_init: val)
          synth.github_repository("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'github_repository', "bool_#{val}")
          expect(config['auto_init']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts delete_branch_on_merge=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(delete_branch_on_merge: val)
          synth.github_repository("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'github_repository', "bool_#{val}")
          expect(config['delete_branch_on_merge']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts has_discussions=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(has_discussions: val)
          synth.github_repository("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'github_repository', "bool_#{val}")
          expect(config['has_discussions']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts has_downloads=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(has_downloads: val)
          synth.github_repository("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'github_repository', "bool_#{val}")
          expect(config['has_downloads']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts has_issues=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(has_issues: val)
          synth.github_repository("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'github_repository', "bool_#{val}")
          expect(config['has_issues']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts has_projects=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(has_projects: val)
          synth.github_repository("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'github_repository', "bool_#{val}")
          expect(config['has_projects']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts has_wiki=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(has_wiki: val)
          synth.github_repository("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'github_repository', "bool_#{val}")
          expect(config['has_wiki']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts ignore_vulnerability_alerts_during_read=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(ignore_vulnerability_alerts_during_read: val)
          synth.github_repository("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'github_repository', "bool_#{val}")
          expect(config['ignore_vulnerability_alerts_during_read']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts is_template=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(is_template: val)
          synth.github_repository("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'github_repository', "bool_#{val}")
          expect(config['is_template']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts web_commit_signoff_required=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(web_commit_signoff_required: val)
          synth.github_repository("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'github_repository', "bool_#{val}")
          expect(config['web_commit_signoff_required']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_repository', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository('first', required_attrs)
        synth.github_repository('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'github_repository')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :github_repository,
    method: :github_repository,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id, :allow_forking, :default_branch, :etag, :fork, :full_name, :git_clone_url, :html_url, :http_clone_url, :node_id, :primary_language, :private, :repo_id, :source_owner, :source_repo, :ssh_clone_url, :svn_url, :topics, :visibility, :vulnerability_alerts],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:allow_auto_merge, :allow_merge_commit, :allow_rebase_merge, :allow_squash_merge, :allow_update_branch, :archive_on_destroy, :archived, :auto_init, :delete_branch_on_merge, :has_discussions, :has_downloads, :has_issues, :has_projects, :has_wiki, :ignore_vulnerability_alerts_during_read, :is_template, :web_commit_signoff_required]
end
