# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a github_branch_default resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GithubBranchDefault do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { branch: 'test-value', repository: 'test-value' } }

  describe ':github_branch_default' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch_default('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'github_branch_default', 'test')
        validate_required_attributes(config, [:branch, :repository])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_branch_default('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:github_branch_default)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_branch_default('test', required_attrs)

        expect(ref.id).to eq("${github_branch_default.test.id}")
        expect(ref.etag).to eq("${github_branch_default.test.etag}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch_default('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_branch_default', 'test')
        expect(config).not_to have_key('etag')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ etag: 'test-value', rename: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch_default('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_branch_default', 'full')
        expect(config).to have_key('etag')
        expect(config).to have_key('rename')
      end
    end

    context 'optional attributes' do
      it 'includes etag when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch_default('opt', required_attrs.merge(etag: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_branch_default', 'opt')
        expect(config).to have_key('etag')
      end

      it 'omits etag when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch_default('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_branch_default', 'minimal')
        expect(config).not_to have_key('etag')
      end
      it 'includes rename when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch_default('opt', required_attrs.merge(rename: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_branch_default', 'opt')
        expect(config).to have_key('rename')
      end

      it 'omits rename when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch_default('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_branch_default', 'minimal')
        expect(config).not_to have_key('rename')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts rename=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(rename: val)
          synth.github_branch_default("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'github_branch_default', "bool_#{val}")
          expect(config['rename']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch_default('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_branch_default', 'typed')
        expect(config['branch']).to be_a(String)
        expect(config['repository']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch_default('first', required_attrs)
        synth.github_branch_default('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'github_branch_default')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :github_branch_default,
    method: :github_branch_default,
    required_attrs: { branch: 'test-value', repository: 'test-value' },
    expected_outputs: [:id, :etag],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:rename]
end
