# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a github_dependabot_organization_secret_repositories resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GithubDependabotOrganizationSecretRepositories do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { secret_name: 'test-value', selected_repository_ids: [3.14] } }

  describe ':github_dependabot_organization_secret_repositories' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_dependabot_organization_secret_repositories('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'github_dependabot_organization_secret_repositories', 'test')
        validate_required_attributes(config, [:secret_name, :selected_repository_ids])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_dependabot_organization_secret_repositories('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:github_dependabot_organization_secret_repositories)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_dependabot_organization_secret_repositories('test', required_attrs)

        expect(ref.id).to eq("${github_dependabot_organization_secret_repositories.test.id}")
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_dependabot_organization_secret_repositories('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_dependabot_organization_secret_repositories', 'typed')
        expect(config['secret_name']).to be_a(String)
        expect(config['selected_repository_ids']).to be_a(Array)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_dependabot_organization_secret_repositories('first', required_attrs)
        synth.github_dependabot_organization_secret_repositories('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'github_dependabot_organization_secret_repositories')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :github_dependabot_organization_secret_repositories,
    method: :github_dependabot_organization_secret_repositories,
    required_attrs: { secret_name: 'test-value', selected_repository_ids: [3.14] },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
