# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a github_actions_variable resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GithubActionsVariable do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { repository: 'test-value', value: 'test-value', variable_name: 'test-value' } }

  describe ':github_actions_variable' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_actions_variable('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'github_actions_variable', 'test')
        validate_required_attributes(config, [:repository, :value, :variable_name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_actions_variable('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:github_actions_variable)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_actions_variable('test', required_attrs)

        expect(ref.id).to eq("${github_actions_variable.test.id}")
        expect(ref.created_at).to eq("${github_actions_variable.test.created_at}")
        expect(ref.repository_id).to eq("${github_actions_variable.test.repository_id}")
        expect(ref.updated_at).to eq("${github_actions_variable.test.updated_at}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_actions_variable('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_actions_variable', 'test')
        expect(config).not_to have_key('created_at')
        expect(config).not_to have_key('repository_id')
        expect(config).not_to have_key('updated_at')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_actions_variable('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_actions_variable', 'typed')
        expect(config['repository']).to be_a(String)
        expect(config['value']).to be_a(String)
        expect(config['variable_name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_actions_variable('first', required_attrs)
        synth.github_actions_variable('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'github_actions_variable')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :github_actions_variable,
    method: :github_actions_variable,
    required_attrs: { repository: 'test-value', value: 'test-value', variable_name: 'test-value' },
    expected_outputs: [:id, :created_at, :repository_id, :updated_at],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
