# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a github_actions_runner_group resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GithubActionsRunnerGroup do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', visibility: 'test-value' } }

  describe ':github_actions_runner_group' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_actions_runner_group('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'github_actions_runner_group', 'test')
        validate_required_attributes(config, [:name, :visibility])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_actions_runner_group('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:github_actions_runner_group)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_actions_runner_group('test', required_attrs)

        expect(ref.id).to eq("${github_actions_runner_group.test.id}")
        expect(ref.default).to eq("${github_actions_runner_group.test.default}")
        expect(ref.etag).to eq("${github_actions_runner_group.test.etag}")
        expect(ref.inherited).to eq("${github_actions_runner_group.test.inherited}")
        expect(ref.runners_url).to eq("${github_actions_runner_group.test.runners_url}")
        expect(ref.selected_repositories_url).to eq("${github_actions_runner_group.test.selected_repositories_url}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_actions_runner_group('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_actions_runner_group', 'test')
        expect(config).not_to have_key('default')
        expect(config).not_to have_key('etag')
        expect(config).not_to have_key('inherited')
        expect(config).not_to have_key('runners_url')
        expect(config).not_to have_key('selected_repositories_url')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ allows_public_repositories: true, restricted_to_workflows: true, selected_repository_ids: [3.14], selected_workflows: ['test-value'] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_actions_runner_group('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_actions_runner_group', 'full')
        expect(config).to have_key('allows_public_repositories')
        expect(config).to have_key('restricted_to_workflows')
        expect(config).to have_key('selected_repository_ids')
        expect(config).to have_key('selected_workflows')
      end
    end

    context 'optional attributes' do
      it 'includes allows_public_repositories when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_actions_runner_group('opt', required_attrs.merge(allows_public_repositories: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_actions_runner_group', 'opt')
        expect(config).to have_key('allows_public_repositories')
      end

      it 'omits allows_public_repositories when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_actions_runner_group('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_actions_runner_group', 'minimal')
        expect(config).not_to have_key('allows_public_repositories')
      end
      it 'includes restricted_to_workflows when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_actions_runner_group('opt', required_attrs.merge(restricted_to_workflows: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_actions_runner_group', 'opt')
        expect(config).to have_key('restricted_to_workflows')
      end

      it 'omits restricted_to_workflows when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_actions_runner_group('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_actions_runner_group', 'minimal')
        expect(config).not_to have_key('restricted_to_workflows')
      end
      it 'includes selected_repository_ids when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_actions_runner_group('opt', required_attrs.merge(selected_repository_ids: [3.14]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_actions_runner_group', 'opt')
        expect(config).to have_key('selected_repository_ids')
      end

      it 'omits selected_repository_ids when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_actions_runner_group('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_actions_runner_group', 'minimal')
        expect(config).not_to have_key('selected_repository_ids')
      end
      it 'includes selected_workflows when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_actions_runner_group('opt', required_attrs.merge(selected_workflows: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_actions_runner_group', 'opt')
        expect(config).to have_key('selected_workflows')
      end

      it 'omits selected_workflows when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_actions_runner_group('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_actions_runner_group', 'minimal')
        expect(config).not_to have_key('selected_workflows')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts allows_public_repositories=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(allows_public_repositories: val)
          synth.github_actions_runner_group("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'github_actions_runner_group', "bool_#{val}")
          expect(config['allows_public_repositories']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts restricted_to_workflows=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(restricted_to_workflows: val)
          synth.github_actions_runner_group("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'github_actions_runner_group', "bool_#{val}")
          expect(config['restricted_to_workflows']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_actions_runner_group('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_actions_runner_group', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['visibility']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_actions_runner_group('first', required_attrs)
        synth.github_actions_runner_group('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'github_actions_runner_group')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :github_actions_runner_group,
    method: :github_actions_runner_group,
    required_attrs: { name: 'test-value', visibility: 'test-value' },
    expected_outputs: [:id, :default, :etag, :inherited, :runners_url, :selected_repositories_url],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:allows_public_repositories, :restricted_to_workflows]
end
