# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a github_repository_collaborator resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GithubRepositoryCollaborator do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { repository: 'test-value', username: 'test-value' } }

  describe ':github_repository_collaborator' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_collaborator('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'github_repository_collaborator', 'test')
        validate_required_attributes(config, [:repository, :username])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_repository_collaborator('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:github_repository_collaborator)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_repository_collaborator('test', required_attrs)

        expect(ref.id).to eq("${github_repository_collaborator.test.id}")
        expect(ref.invitation_id).to eq("${github_repository_collaborator.test.invitation_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_collaborator('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_repository_collaborator', 'test')
        expect(config).not_to have_key('invitation_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ permission: 'test-value', permission_diff_suppression: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_collaborator('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_repository_collaborator', 'full')
        expect(config).to have_key('permission')
        expect(config).to have_key('permission_diff_suppression')
      end
    end

    context 'optional attributes' do
      it 'includes permission when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_collaborator('opt', required_attrs.merge(permission: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository_collaborator', 'opt')
        expect(config).to have_key('permission')
      end

      it 'omits permission when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_collaborator('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository_collaborator', 'minimal')
        expect(config).not_to have_key('permission')
      end
      it 'includes permission_diff_suppression when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_collaborator('opt', required_attrs.merge(permission_diff_suppression: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository_collaborator', 'opt')
        expect(config).to have_key('permission_diff_suppression')
      end

      it 'omits permission_diff_suppression when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_collaborator('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository_collaborator', 'minimal')
        expect(config).not_to have_key('permission_diff_suppression')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts permission_diff_suppression=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(permission_diff_suppression: val)
          synth.github_repository_collaborator("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'github_repository_collaborator', "bool_#{val}")
          expect(config['permission_diff_suppression']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_collaborator('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_repository_collaborator', 'typed')
        expect(config['repository']).to be_a(String)
        expect(config['username']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_collaborator('first', required_attrs)
        synth.github_repository_collaborator('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'github_repository_collaborator')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :github_repository_collaborator,
    method: :github_repository_collaborator,
    required_attrs: { repository: 'test-value', username: 'test-value' },
    expected_outputs: [:id, :invitation_id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:permission_diff_suppression]
end
