# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a github_organization_repository_role resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GithubOrganizationRepositoryRole do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { base_role: 'test-value', name: 'test-value', permissions: ['test-value'] } }

  describe ':github_organization_repository_role' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_organization_repository_role('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'github_organization_repository_role', 'test')
        validate_required_attributes(config, [:base_role, :name, :permissions])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_organization_repository_role('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:github_organization_repository_role)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_organization_repository_role('test', required_attrs)

        expect(ref.id).to eq("${github_organization_repository_role.test.id}")
        expect(ref.role_id).to eq("${github_organization_repository_role.test.role_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_organization_repository_role('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_organization_repository_role', 'test')
        expect(config).not_to have_key('role_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ description: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_organization_repository_role('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_organization_repository_role', 'full')
        expect(config).to have_key('description')
      end
    end

    context 'optional attributes' do
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_organization_repository_role('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_organization_repository_role', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_organization_repository_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_organization_repository_role', 'minimal')
        expect(config).not_to have_key('description')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_organization_repository_role('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_organization_repository_role', 'typed')
        expect(config['base_role']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['permissions']).to be_a(Array)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_organization_repository_role('first', required_attrs)
        synth.github_organization_repository_role('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'github_organization_repository_role')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :github_organization_repository_role,
    method: :github_organization_repository_role,
    required_attrs: { base_role: 'test-value', name: 'test-value', permissions: ['test-value'] },
    expected_outputs: [:id, :role_id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
