# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a github_membership resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GithubMembership do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { username: 'test-value' } }

  describe ':github_membership' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_membership('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'github_membership', 'test')
        validate_required_attributes(config, [:username])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_membership('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:github_membership)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_membership('test', required_attrs)

        expect(ref.id).to eq("${github_membership.test.id}")
        expect(ref.etag).to eq("${github_membership.test.etag}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_membership('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_membership', 'test')
        expect(config).not_to have_key('etag')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ downgrade_on_destroy: true, role: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_membership('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_membership', 'full')
        expect(config).to have_key('downgrade_on_destroy')
        expect(config).to have_key('role')
      end
    end

    context 'optional attributes' do
      it 'includes downgrade_on_destroy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_membership('opt', required_attrs.merge(downgrade_on_destroy: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_membership', 'opt')
        expect(config).to have_key('downgrade_on_destroy')
      end

      it 'omits downgrade_on_destroy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_membership('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_membership', 'minimal')
        expect(config).not_to have_key('downgrade_on_destroy')
      end
      it 'includes role when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_membership('opt', required_attrs.merge(role: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_membership', 'opt')
        expect(config).to have_key('role')
      end

      it 'omits role when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_membership('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_membership', 'minimal')
        expect(config).not_to have_key('role')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts downgrade_on_destroy=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(downgrade_on_destroy: val)
          synth.github_membership("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'github_membership', "bool_#{val}")
          expect(config['downgrade_on_destroy']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_membership('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_membership', 'typed')
        expect(config['username']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_membership('first', required_attrs)
        synth.github_membership('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'github_membership')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :github_membership,
    method: :github_membership,
    required_attrs: { username: 'test-value' },
    expected_outputs: [:id, :etag],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:downgrade_on_destroy]
end
