# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a github_repository_collaborators resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GithubRepositoryCollaborators do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { repository: 'test-value' } }

  describe ':github_repository_collaborators' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_collaborators('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'github_repository_collaborators', 'test')
        validate_required_attributes(config, [:repository])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_repository_collaborators('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:github_repository_collaborators)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_repository_collaborators('test', required_attrs)

        expect(ref.id).to eq("${github_repository_collaborators.test.id}")
        expect(ref.invitation_ids).to eq("${github_repository_collaborators.test.invitation_ids}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_collaborators('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_repository_collaborators', 'test')
        expect(config).not_to have_key('invitation_ids')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ ignore_team: [{ 'key1' => 'val1' }], team: [{ 'key1' => 'val1' }], user: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_collaborators('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_repository_collaborators', 'full')
        expect(config).to have_key('ignore_team')
        expect(config).to have_key('team')
        expect(config).to have_key('user')
      end
    end

    context 'optional attributes' do
      it 'includes ignore_team when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_collaborators('opt', required_attrs.merge(ignore_team: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository_collaborators', 'opt')
        expect(config).to have_key('ignore_team')
      end

      it 'omits ignore_team when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_collaborators('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository_collaborators', 'minimal')
        expect(config).not_to have_key('ignore_team')
      end
      it 'includes team when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_collaborators('opt', required_attrs.merge(team: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository_collaborators', 'opt')
        expect(config).to have_key('team')
      end

      it 'omits team when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_collaborators('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository_collaborators', 'minimal')
        expect(config).not_to have_key('team')
      end
      it 'includes user when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_collaborators('opt', required_attrs.merge(user: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository_collaborators', 'opt')
        expect(config).to have_key('user')
      end

      it 'omits user when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_collaborators('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository_collaborators', 'minimal')
        expect(config).not_to have_key('user')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_collaborators('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_repository_collaborators', 'typed')
        expect(config['repository']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_collaborators('first', required_attrs)
        synth.github_repository_collaborators('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'github_repository_collaborators')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :github_repository_collaborators,
    method: :github_repository_collaborators,
    required_attrs: { repository: 'test-value' },
    expected_outputs: [:id, :invitation_ids],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
