# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a github_actions_repository_oidc_subject_claim_customization_template resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GithubActionsRepositoryOidcSubjectClaimCustomizationTemplate do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { repository: 'test-value', use_default: true } }

  describe ':github_actions_repository_oidc_subject_claim_customization_template' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_actions_repository_oidc_subject_claim_customization_template('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'github_actions_repository_oidc_subject_claim_customization_template', 'test')
        validate_required_attributes(config, [:repository, :use_default])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_actions_repository_oidc_subject_claim_customization_template('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:github_actions_repository_oidc_subject_claim_customization_template)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_actions_repository_oidc_subject_claim_customization_template('test', required_attrs)

        expect(ref.id).to eq("${github_actions_repository_oidc_subject_claim_customization_template.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ include_claim_keys: ['test-value'] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_actions_repository_oidc_subject_claim_customization_template('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_actions_repository_oidc_subject_claim_customization_template', 'full')
        expect(config).to have_key('include_claim_keys')
      end
    end

    context 'optional attributes' do
      it 'includes include_claim_keys when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_actions_repository_oidc_subject_claim_customization_template('opt', required_attrs.merge(include_claim_keys: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_actions_repository_oidc_subject_claim_customization_template', 'opt')
        expect(config).to have_key('include_claim_keys')
      end

      it 'omits include_claim_keys when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_actions_repository_oidc_subject_claim_customization_template('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_actions_repository_oidc_subject_claim_customization_template', 'minimal')
        expect(config).not_to have_key('include_claim_keys')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts use_default=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(use_default: val)
          synth.github_actions_repository_oidc_subject_claim_customization_template("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'github_actions_repository_oidc_subject_claim_customization_template', "bool_#{val}")
          expect(config['use_default']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_actions_repository_oidc_subject_claim_customization_template('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_actions_repository_oidc_subject_claim_customization_template', 'typed')
        expect(config['repository']).to be_a(String)
        expect([true, false]).to include(config['use_default'])
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_actions_repository_oidc_subject_claim_customization_template('first', required_attrs)
        synth.github_actions_repository_oidc_subject_claim_customization_template('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'github_actions_repository_oidc_subject_claim_customization_template')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :github_actions_repository_oidc_subject_claim_customization_template,
    method: :github_actions_repository_oidc_subject_claim_customization_template,
    required_attrs: { repository: 'test-value', use_default: true },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:use_default]
end
