# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a github_user_invitation_accepter resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GithubUserInvitationAccepter do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { {} }

  describe ':github_user_invitation_accepter' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_user_invitation_accepter('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'github_user_invitation_accepter', 'test')
        validate_required_attributes(config, [])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_user_invitation_accepter('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:github_user_invitation_accepter)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_user_invitation_accepter('test', required_attrs)

        expect(ref.id).to eq("${github_user_invitation_accepter.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ allow_empty_id: true, invitation_id: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_user_invitation_accepter('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_user_invitation_accepter', 'full')
        expect(config).to have_key('allow_empty_id')
        expect(config).to have_key('invitation_id')
      end
    end

    context 'optional attributes' do
      it 'includes allow_empty_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_user_invitation_accepter('opt', required_attrs.merge(allow_empty_id: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_user_invitation_accepter', 'opt')
        expect(config).to have_key('allow_empty_id')
      end

      it 'omits allow_empty_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_user_invitation_accepter('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_user_invitation_accepter', 'minimal')
        expect(config).not_to have_key('allow_empty_id')
      end
      it 'includes invitation_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_user_invitation_accepter('opt', required_attrs.merge(invitation_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_user_invitation_accepter', 'opt')
        expect(config).to have_key('invitation_id')
      end

      it 'omits invitation_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_user_invitation_accepter('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_user_invitation_accepter', 'minimal')
        expect(config).not_to have_key('invitation_id')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts allow_empty_id=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(allow_empty_id: val)
          synth.github_user_invitation_accepter("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'github_user_invitation_accepter', "bool_#{val}")
          expect(config['allow_empty_id']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_user_invitation_accepter('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_user_invitation_accepter', 'typed')
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_user_invitation_accepter('first', required_attrs)
        synth.github_user_invitation_accepter('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'github_user_invitation_accepter')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :github_user_invitation_accepter,
    method: :github_user_invitation_accepter,
    required_attrs: {},
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:allow_empty_id]
end
