# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a github_project_card resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GithubProjectCard do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { column_id: 'test-value' } }

  describe ':github_project_card' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_project_card('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'github_project_card', 'test')
        validate_required_attributes(config, [:column_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_project_card('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:github_project_card)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_project_card('test', required_attrs)

        expect(ref.id).to eq("${github_project_card.test.id}")
        expect(ref.card_id).to eq("${github_project_card.test.card_id}")
        expect(ref.etag).to eq("${github_project_card.test.etag}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_project_card('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_project_card', 'test')
        expect(config).not_to have_key('card_id')
        expect(config).not_to have_key('etag')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ content_id: 3.14, content_type: 'test-value', note: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_project_card('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_project_card', 'full')
        expect(config).to have_key('content_id')
        expect(config).to have_key('content_type')
        expect(config).to have_key('note')
      end
    end

    context 'optional attributes' do
      it 'includes content_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_project_card('opt', required_attrs.merge(content_id: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_project_card', 'opt')
        expect(config).to have_key('content_id')
      end

      it 'omits content_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_project_card('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_project_card', 'minimal')
        expect(config).not_to have_key('content_id')
      end
      it 'includes content_type when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_project_card('opt', required_attrs.merge(content_type: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_project_card', 'opt')
        expect(config).to have_key('content_type')
      end

      it 'omits content_type when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_project_card('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_project_card', 'minimal')
        expect(config).not_to have_key('content_type')
      end
      it 'includes note when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_project_card('opt', required_attrs.merge(note: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_project_card', 'opt')
        expect(config).to have_key('note')
      end

      it 'omits note when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_project_card('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_project_card', 'minimal')
        expect(config).not_to have_key('note')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_project_card('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_project_card', 'typed')
        expect(config['column_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_project_card('first', required_attrs)
        synth.github_project_card('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'github_project_card')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :github_project_card,
    method: :github_project_card,
    required_attrs: { column_id: 'test-value' },
    expected_outputs: [:id, :card_id, :etag],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
