# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a github_user_gpg_key resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GithubUserGpgKey do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { armored_public_key: 'test-value' } }

  describe ':github_user_gpg_key' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_user_gpg_key('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'github_user_gpg_key', 'test')
        validate_required_attributes(config, [:armored_public_key])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_user_gpg_key('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:github_user_gpg_key)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_user_gpg_key('test', required_attrs)

        expect(ref.id).to eq("${github_user_gpg_key.test.id}")
        expect(ref.etag).to eq("${github_user_gpg_key.test.etag}")
        expect(ref.key_id).to eq("${github_user_gpg_key.test.key_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_user_gpg_key('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_user_gpg_key', 'test')
        expect(config).not_to have_key('etag')
        expect(config).not_to have_key('key_id')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_user_gpg_key('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_user_gpg_key', 'typed')
        expect(config['armored_public_key']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_user_gpg_key('first', required_attrs)
        synth.github_user_gpg_key('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'github_user_gpg_key')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :github_user_gpg_key,
    method: :github_user_gpg_key,
    required_attrs: { armored_public_key: 'test-value' },
    expected_outputs: [:id, :etag, :key_id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
