# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a github_branch resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GithubBranch do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { branch: 'test-value', repository: 'test-value' } }

  describe ':github_branch' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'github_branch', 'test')
        validate_required_attributes(config, [:branch, :repository])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_branch('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:github_branch)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_branch('test', required_attrs)

        expect(ref.id).to eq("${github_branch.test.id}")
        expect(ref.etag).to eq("${github_branch.test.etag}")
        expect(ref.ref).to eq("${github_branch.test.ref}")
        expect(ref.sha).to eq("${github_branch.test.sha}")
        expect(ref.source_sha).to eq("${github_branch.test.source_sha}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_branch', 'test')
        expect(config).not_to have_key('etag')
        expect(config).not_to have_key('ref')
        expect(config).not_to have_key('sha')
        expect(config).not_to have_key('source_sha')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ source_branch: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_branch', 'full')
        expect(config).to have_key('source_branch')
      end
    end

    context 'optional attributes' do
      it 'includes source_branch when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch('opt', required_attrs.merge(source_branch: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_branch', 'opt')
        expect(config).to have_key('source_branch')
      end

      it 'omits source_branch when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_branch', 'minimal')
        expect(config).not_to have_key('source_branch')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_branch', 'typed')
        expect(config['branch']).to be_a(String)
        expect(config['repository']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch('first', required_attrs)
        synth.github_branch('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'github_branch')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :github_branch,
    method: :github_branch,
    required_attrs: { branch: 'test-value', repository: 'test-value' },
    expected_outputs: [:id, :etag, :ref, :sha, :source_sha],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
