# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a github_branch_protection_v3 resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GithubBranchProtectionV3 do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { branch: 'test-value', repository: 'test-value' } }

  describe ':github_branch_protection_v3' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch_protection_v3('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'github_branch_protection_v3', 'test')
        validate_required_attributes(config, [:branch, :repository])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_branch_protection_v3('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:github_branch_protection_v3)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_branch_protection_v3('test', required_attrs)

        expect(ref.id).to eq("${github_branch_protection_v3.test.id}")
        expect(ref.etag).to eq("${github_branch_protection_v3.test.etag}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch_protection_v3('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_branch_protection_v3', 'test')
        expect(config).not_to have_key('etag')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ enforce_admins: true, require_conversation_resolution: true, require_signed_commits: true, required_pull_request_reviews: { 'key1' => 'val1' }, required_status_checks: { 'key1' => 'val1' }, restrictions: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch_protection_v3('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_branch_protection_v3', 'full')
        expect(config).to have_key('enforce_admins')
        expect(config).to have_key('require_conversation_resolution')
        expect(config).to have_key('require_signed_commits')
        expect(config).to have_key('required_pull_request_reviews')
        expect(config).to have_key('required_status_checks')
        expect(config).to have_key('restrictions')
      end
    end

    context 'optional attributes' do
      it 'includes enforce_admins when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch_protection_v3('opt', required_attrs.merge(enforce_admins: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_branch_protection_v3', 'opt')
        expect(config).to have_key('enforce_admins')
      end

      it 'omits enforce_admins when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch_protection_v3('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_branch_protection_v3', 'minimal')
        expect(config).not_to have_key('enforce_admins')
      end
      it 'includes require_conversation_resolution when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch_protection_v3('opt', required_attrs.merge(require_conversation_resolution: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_branch_protection_v3', 'opt')
        expect(config).to have_key('require_conversation_resolution')
      end

      it 'omits require_conversation_resolution when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch_protection_v3('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_branch_protection_v3', 'minimal')
        expect(config).not_to have_key('require_conversation_resolution')
      end
      it 'includes require_signed_commits when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch_protection_v3('opt', required_attrs.merge(require_signed_commits: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_branch_protection_v3', 'opt')
        expect(config).to have_key('require_signed_commits')
      end

      it 'omits require_signed_commits when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch_protection_v3('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_branch_protection_v3', 'minimal')
        expect(config).not_to have_key('require_signed_commits')
      end
      it 'includes required_pull_request_reviews when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch_protection_v3('opt', required_attrs.merge(required_pull_request_reviews: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_branch_protection_v3', 'opt')
        expect(config).to have_key('required_pull_request_reviews')
      end

      it 'omits required_pull_request_reviews when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch_protection_v3('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_branch_protection_v3', 'minimal')
        expect(config).not_to have_key('required_pull_request_reviews')
      end
      it 'includes required_status_checks when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch_protection_v3('opt', required_attrs.merge(required_status_checks: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_branch_protection_v3', 'opt')
        expect(config).to have_key('required_status_checks')
      end

      it 'omits required_status_checks when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch_protection_v3('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_branch_protection_v3', 'minimal')
        expect(config).not_to have_key('required_status_checks')
      end
      it 'includes restrictions when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch_protection_v3('opt', required_attrs.merge(restrictions: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_branch_protection_v3', 'opt')
        expect(config).to have_key('restrictions')
      end

      it 'omits restrictions when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch_protection_v3('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_branch_protection_v3', 'minimal')
        expect(config).not_to have_key('restrictions')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts enforce_admins=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(enforce_admins: val)
          synth.github_branch_protection_v3("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'github_branch_protection_v3', "bool_#{val}")
          expect(config['enforce_admins']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts require_conversation_resolution=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(require_conversation_resolution: val)
          synth.github_branch_protection_v3("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'github_branch_protection_v3', "bool_#{val}")
          expect(config['require_conversation_resolution']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts require_signed_commits=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(require_signed_commits: val)
          synth.github_branch_protection_v3("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'github_branch_protection_v3', "bool_#{val}")
          expect(config['require_signed_commits']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch_protection_v3('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_branch_protection_v3', 'typed')
        expect(config['branch']).to be_a(String)
        expect(config['repository']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch_protection_v3('first', required_attrs)
        synth.github_branch_protection_v3('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'github_branch_protection_v3')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :github_branch_protection_v3,
    method: :github_branch_protection_v3,
    required_attrs: { branch: 'test-value', repository: 'test-value' },
    expected_outputs: [:id, :etag],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:enforce_admins, :require_conversation_resolution, :require_signed_commits]
end
