# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a github_team resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GithubTeam do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':github_team' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_team('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'github_team', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_team('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:github_team)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_team('test', required_attrs)

        expect(ref.id).to eq("${github_team.test.id}")
        expect(ref.etag).to eq("${github_team.test.etag}")
        expect(ref.members_count).to eq("${github_team.test.members_count}")
        expect(ref.node_id).to eq("${github_team.test.node_id}")
        expect(ref.parent_team_read_id).to eq("${github_team.test.parent_team_read_id}")
        expect(ref.parent_team_read_slug).to eq("${github_team.test.parent_team_read_slug}")
        expect(ref.slug).to eq("${github_team.test.slug}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_team('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_team', 'test')
        expect(config).not_to have_key('etag')
        expect(config).not_to have_key('members_count')
        expect(config).not_to have_key('node_id')
        expect(config).not_to have_key('parent_team_read_id')
        expect(config).not_to have_key('parent_team_read_slug')
        expect(config).not_to have_key('slug')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ create_default_maintainer: true, description: 'test-value', ldap_dn: 'test-value', notification_setting: 'test-value', parent_team_id: 'test-value', parent_team_read_id: 'test-value', parent_team_read_slug: 'test-value', privacy: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_team('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_team', 'full')
        expect(config).to have_key('create_default_maintainer')
        expect(config).to have_key('description')
        expect(config).to have_key('ldap_dn')
        expect(config).to have_key('notification_setting')
        expect(config).to have_key('parent_team_id')
        expect(config).to have_key('parent_team_read_id')
        expect(config).to have_key('parent_team_read_slug')
        expect(config).to have_key('privacy')
      end
    end

    context 'optional attributes' do
      it 'includes create_default_maintainer when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_team('opt', required_attrs.merge(create_default_maintainer: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_team', 'opt')
        expect(config).to have_key('create_default_maintainer')
      end

      it 'omits create_default_maintainer when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_team('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_team', 'minimal')
        expect(config).not_to have_key('create_default_maintainer')
      end
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_team('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_team', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_team('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_team', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes ldap_dn when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_team('opt', required_attrs.merge(ldap_dn: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_team', 'opt')
        expect(config).to have_key('ldap_dn')
      end

      it 'omits ldap_dn when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_team('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_team', 'minimal')
        expect(config).not_to have_key('ldap_dn')
      end
      it 'includes notification_setting when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_team('opt', required_attrs.merge(notification_setting: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_team', 'opt')
        expect(config).to have_key('notification_setting')
      end

      it 'omits notification_setting when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_team('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_team', 'minimal')
        expect(config).not_to have_key('notification_setting')
      end
      it 'includes parent_team_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_team('opt', required_attrs.merge(parent_team_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_team', 'opt')
        expect(config).to have_key('parent_team_id')
      end

      it 'omits parent_team_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_team('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_team', 'minimal')
        expect(config).not_to have_key('parent_team_id')
      end
      it 'includes parent_team_read_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_team('opt', required_attrs.merge(parent_team_read_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_team', 'opt')
        expect(config).to have_key('parent_team_read_id')
      end

      it 'omits parent_team_read_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_team('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_team', 'minimal')
        expect(config).not_to have_key('parent_team_read_id')
      end
      it 'includes parent_team_read_slug when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_team('opt', required_attrs.merge(parent_team_read_slug: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_team', 'opt')
        expect(config).to have_key('parent_team_read_slug')
      end

      it 'omits parent_team_read_slug when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_team('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_team', 'minimal')
        expect(config).not_to have_key('parent_team_read_slug')
      end
      it 'includes privacy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_team('opt', required_attrs.merge(privacy: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_team', 'opt')
        expect(config).to have_key('privacy')
      end

      it 'omits privacy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_team('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_team', 'minimal')
        expect(config).not_to have_key('privacy')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts create_default_maintainer=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(create_default_maintainer: val)
          synth.github_team("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'github_team', "bool_#{val}")
          expect(config['create_default_maintainer']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_team('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_team', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_team('first', required_attrs)
        synth.github_team('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'github_team')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :github_team,
    method: :github_team,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id, :etag, :members_count, :node_id, :parent_team_read_id, :parent_team_read_slug, :slug],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:create_default_maintainer]
end
