# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a github_repository_file resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GithubRepositoryFile do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { content: 'test-value', file: 'test-value', repository: 'test-value' } }

  describe ':github_repository_file' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_file('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'github_repository_file', 'test')
        validate_required_attributes(config, [:content, :file, :repository])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_repository_file('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:github_repository_file)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_repository_file('test', required_attrs)

        expect(ref.id).to eq("${github_repository_file.test.id}")
        expect(ref.autocreate_branch_source_sha).to eq("${github_repository_file.test.autocreate_branch_source_sha}")
        expect(ref.branch).to eq("${github_repository_file.test.branch}")
        expect(ref.commit_message).to eq("${github_repository_file.test.commit_message}")
        expect(ref.commit_sha).to eq("${github_repository_file.test.commit_sha}")
        expect(ref.ref).to eq("${github_repository_file.test.ref}")
        expect(ref.repository_id).to eq("${github_repository_file.test.repository_id}")
        expect(ref.sha).to eq("${github_repository_file.test.sha}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_file('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_repository_file', 'test')
        expect(config).not_to have_key('autocreate_branch_source_sha')
        expect(config).not_to have_key('branch')
        expect(config).not_to have_key('commit_message')
        expect(config).not_to have_key('commit_sha')
        expect(config).not_to have_key('ref')
        expect(config).not_to have_key('repository_id')
        expect(config).not_to have_key('sha')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ autocreate_branch: true, autocreate_branch_source_branch: 'test-value', commit_author: 'test-value', commit_email: 'test-value', overwrite_on_create: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_file('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_repository_file', 'full')
        expect(config).to have_key('autocreate_branch')
        expect(config).to have_key('autocreate_branch_source_branch')
        expect(config).to have_key('commit_author')
        expect(config).to have_key('commit_email')
        expect(config).to have_key('overwrite_on_create')
      end
    end

    context 'optional attributes' do
      it 'includes autocreate_branch when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_file('opt', required_attrs.merge(autocreate_branch: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository_file', 'opt')
        expect(config).to have_key('autocreate_branch')
      end

      it 'omits autocreate_branch when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_file('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository_file', 'minimal')
        expect(config).not_to have_key('autocreate_branch')
      end
      it 'includes autocreate_branch_source_branch when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_file('opt', required_attrs.merge(autocreate_branch_source_branch: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository_file', 'opt')
        expect(config).to have_key('autocreate_branch_source_branch')
      end

      it 'omits autocreate_branch_source_branch when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_file('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository_file', 'minimal')
        expect(config).not_to have_key('autocreate_branch_source_branch')
      end
      it 'includes commit_author when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_file('opt', required_attrs.merge(commit_author: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository_file', 'opt')
        expect(config).to have_key('commit_author')
      end

      it 'omits commit_author when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_file('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository_file', 'minimal')
        expect(config).not_to have_key('commit_author')
      end
      it 'includes commit_email when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_file('opt', required_attrs.merge(commit_email: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository_file', 'opt')
        expect(config).to have_key('commit_email')
      end

      it 'omits commit_email when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_file('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository_file', 'minimal')
        expect(config).not_to have_key('commit_email')
      end
      it 'includes overwrite_on_create when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_file('opt', required_attrs.merge(overwrite_on_create: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository_file', 'opt')
        expect(config).to have_key('overwrite_on_create')
      end

      it 'omits overwrite_on_create when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_file('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository_file', 'minimal')
        expect(config).not_to have_key('overwrite_on_create')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts autocreate_branch=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(autocreate_branch: val)
          synth.github_repository_file("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'github_repository_file', "bool_#{val}")
          expect(config['autocreate_branch']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts overwrite_on_create=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(overwrite_on_create: val)
          synth.github_repository_file("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'github_repository_file', "bool_#{val}")
          expect(config['overwrite_on_create']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_file('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_repository_file', 'typed')
        expect(config['content']).to be_a(String)
        expect(config['file']).to be_a(String)
        expect(config['repository']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_file('first', required_attrs)
        synth.github_repository_file('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'github_repository_file')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :github_repository_file,
    method: :github_repository_file,
    required_attrs: { content: 'test-value', file: 'test-value', repository: 'test-value' },
    expected_outputs: [:id, :autocreate_branch_source_sha, :branch, :commit_message, :commit_sha, :ref, :repository_id, :sha],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:autocreate_branch, :overwrite_on_create]
end
