# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a github_repository_milestone resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GithubRepositoryMilestone do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { owner: 'test-value', repository: 'test-value', title: 'test-value' } }

  describe ':github_repository_milestone' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_milestone('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'github_repository_milestone', 'test')
        validate_required_attributes(config, [:owner, :repository, :title])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_repository_milestone('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:github_repository_milestone)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_repository_milestone('test', required_attrs)

        expect(ref.id).to eq("${github_repository_milestone.test.id}")
        expect(ref.number).to eq("${github_repository_milestone.test.number}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_milestone('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_repository_milestone', 'test')
        expect(config).not_to have_key('number')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ description: 'test-value', due_date: 'test-value', state: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_milestone('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_repository_milestone', 'full')
        expect(config).to have_key('description')
        expect(config).to have_key('due_date')
        expect(config).to have_key('state')
      end
    end

    context 'optional attributes' do
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_milestone('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository_milestone', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_milestone('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository_milestone', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes due_date when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_milestone('opt', required_attrs.merge(due_date: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository_milestone', 'opt')
        expect(config).to have_key('due_date')
      end

      it 'omits due_date when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_milestone('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository_milestone', 'minimal')
        expect(config).not_to have_key('due_date')
      end
      it 'includes state when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_milestone('opt', required_attrs.merge(state: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository_milestone', 'opt')
        expect(config).to have_key('state')
      end

      it 'omits state when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_milestone('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_repository_milestone', 'minimal')
        expect(config).not_to have_key('state')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_milestone('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_repository_milestone', 'typed')
        expect(config['owner']).to be_a(String)
        expect(config['repository']).to be_a(String)
        expect(config['title']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_milestone('first', required_attrs)
        synth.github_repository_milestone('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'github_repository_milestone')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :github_repository_milestone,
    method: :github_repository_milestone,
    required_attrs: { owner: 'test-value', repository: 'test-value', title: 'test-value' },
    expected_outputs: [:id, :number],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
