# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a github_issue_labels resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GithubIssueLabels do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { repository: 'test-value' } }

  describe ':github_issue_labels' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_issue_labels('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'github_issue_labels', 'test')
        validate_required_attributes(config, [:repository])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_issue_labels('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:github_issue_labels)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_issue_labels('test', required_attrs)

        expect(ref.id).to eq("${github_issue_labels.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ label: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_issue_labels('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_issue_labels', 'full')
        expect(config).to have_key('label')
      end
    end

    context 'optional attributes' do
      it 'includes label when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_issue_labels('opt', required_attrs.merge(label: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_issue_labels', 'opt')
        expect(config).to have_key('label')
      end

      it 'omits label when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_issue_labels('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_issue_labels', 'minimal')
        expect(config).not_to have_key('label')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_issue_labels('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_issue_labels', 'typed')
        expect(config['repository']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_issue_labels('first', required_attrs)
        synth.github_issue_labels('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'github_issue_labels')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :github_issue_labels,
    method: :github_issue_labels,
    required_attrs: { repository: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
