# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a github_branch_protection resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GithubBranchProtection do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { pattern: 'test-value', repository_id: 'test-value' } }

  describe ':github_branch_protection' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch_protection('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'github_branch_protection', 'test')
        validate_required_attributes(config, [:pattern, :repository_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_branch_protection('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:github_branch_protection)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_branch_protection('test', required_attrs)

        expect(ref.id).to eq("${github_branch_protection.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ allows_deletions: true, allows_force_pushes: true, enforce_admins: true, force_push_bypassers: ['test-value'], lock_branch: true, require_conversation_resolution: true, require_signed_commits: true, required_linear_history: true, required_pull_request_reviews: [{ 'key1' => 'val1' }], required_status_checks: [{ 'key1' => 'val1' }], restrict_pushes: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch_protection('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_branch_protection', 'full')
        expect(config).to have_key('allows_deletions')
        expect(config).to have_key('allows_force_pushes')
        expect(config).to have_key('enforce_admins')
        expect(config).to have_key('force_push_bypassers')
        expect(config).to have_key('lock_branch')
        expect(config).to have_key('require_conversation_resolution')
        expect(config).to have_key('require_signed_commits')
        expect(config).to have_key('required_linear_history')
        expect(config).to have_key('required_pull_request_reviews')
        expect(config).to have_key('required_status_checks')
        expect(config).to have_key('restrict_pushes')
      end
    end

    context 'optional attributes' do
      it 'includes allows_deletions when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch_protection('opt', required_attrs.merge(allows_deletions: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_branch_protection', 'opt')
        expect(config).to have_key('allows_deletions')
      end

      it 'omits allows_deletions when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch_protection('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_branch_protection', 'minimal')
        expect(config).not_to have_key('allows_deletions')
      end
      it 'includes allows_force_pushes when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch_protection('opt', required_attrs.merge(allows_force_pushes: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_branch_protection', 'opt')
        expect(config).to have_key('allows_force_pushes')
      end

      it 'omits allows_force_pushes when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch_protection('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_branch_protection', 'minimal')
        expect(config).not_to have_key('allows_force_pushes')
      end
      it 'includes enforce_admins when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch_protection('opt', required_attrs.merge(enforce_admins: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_branch_protection', 'opt')
        expect(config).to have_key('enforce_admins')
      end

      it 'omits enforce_admins when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch_protection('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_branch_protection', 'minimal')
        expect(config).not_to have_key('enforce_admins')
      end
      it 'includes force_push_bypassers when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch_protection('opt', required_attrs.merge(force_push_bypassers: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_branch_protection', 'opt')
        expect(config).to have_key('force_push_bypassers')
      end

      it 'omits force_push_bypassers when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch_protection('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_branch_protection', 'minimal')
        expect(config).not_to have_key('force_push_bypassers')
      end
      it 'includes lock_branch when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch_protection('opt', required_attrs.merge(lock_branch: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_branch_protection', 'opt')
        expect(config).to have_key('lock_branch')
      end

      it 'omits lock_branch when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch_protection('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_branch_protection', 'minimal')
        expect(config).not_to have_key('lock_branch')
      end
      it 'includes require_conversation_resolution when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch_protection('opt', required_attrs.merge(require_conversation_resolution: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_branch_protection', 'opt')
        expect(config).to have_key('require_conversation_resolution')
      end

      it 'omits require_conversation_resolution when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch_protection('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_branch_protection', 'minimal')
        expect(config).not_to have_key('require_conversation_resolution')
      end
      it 'includes require_signed_commits when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch_protection('opt', required_attrs.merge(require_signed_commits: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_branch_protection', 'opt')
        expect(config).to have_key('require_signed_commits')
      end

      it 'omits require_signed_commits when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch_protection('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_branch_protection', 'minimal')
        expect(config).not_to have_key('require_signed_commits')
      end
      it 'includes required_linear_history when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch_protection('opt', required_attrs.merge(required_linear_history: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_branch_protection', 'opt')
        expect(config).to have_key('required_linear_history')
      end

      it 'omits required_linear_history when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch_protection('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_branch_protection', 'minimal')
        expect(config).not_to have_key('required_linear_history')
      end
      it 'includes required_pull_request_reviews when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch_protection('opt', required_attrs.merge(required_pull_request_reviews: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_branch_protection', 'opt')
        expect(config).to have_key('required_pull_request_reviews')
      end

      it 'omits required_pull_request_reviews when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch_protection('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_branch_protection', 'minimal')
        expect(config).not_to have_key('required_pull_request_reviews')
      end
      it 'includes required_status_checks when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch_protection('opt', required_attrs.merge(required_status_checks: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_branch_protection', 'opt')
        expect(config).to have_key('required_status_checks')
      end

      it 'omits required_status_checks when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch_protection('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_branch_protection', 'minimal')
        expect(config).not_to have_key('required_status_checks')
      end
      it 'includes restrict_pushes when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch_protection('opt', required_attrs.merge(restrict_pushes: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_branch_protection', 'opt')
        expect(config).to have_key('restrict_pushes')
      end

      it 'omits restrict_pushes when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch_protection('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'github_branch_protection', 'minimal')
        expect(config).not_to have_key('restrict_pushes')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts allows_deletions=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(allows_deletions: val)
          synth.github_branch_protection("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'github_branch_protection', "bool_#{val}")
          expect(config['allows_deletions']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts allows_force_pushes=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(allows_force_pushes: val)
          synth.github_branch_protection("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'github_branch_protection', "bool_#{val}")
          expect(config['allows_force_pushes']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts enforce_admins=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(enforce_admins: val)
          synth.github_branch_protection("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'github_branch_protection', "bool_#{val}")
          expect(config['enforce_admins']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts lock_branch=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(lock_branch: val)
          synth.github_branch_protection("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'github_branch_protection', "bool_#{val}")
          expect(config['lock_branch']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts require_conversation_resolution=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(require_conversation_resolution: val)
          synth.github_branch_protection("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'github_branch_protection', "bool_#{val}")
          expect(config['require_conversation_resolution']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts require_signed_commits=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(require_signed_commits: val)
          synth.github_branch_protection("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'github_branch_protection', "bool_#{val}")
          expect(config['require_signed_commits']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts required_linear_history=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(required_linear_history: val)
          synth.github_branch_protection("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'github_branch_protection', "bool_#{val}")
          expect(config['required_linear_history']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch_protection('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_branch_protection', 'typed')
        expect(config['pattern']).to be_a(String)
        expect(config['repository_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_branch_protection('first', required_attrs)
        synth.github_branch_protection('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'github_branch_protection')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :github_branch_protection,
    method: :github_branch_protection,
    required_attrs: { pattern: 'test-value', repository_id: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:allows_deletions, :allows_force_pushes, :enforce_admins, :lock_branch, :require_conversation_resolution, :require_signed_commits, :required_linear_history]
end
