# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a github_repository_custom_property resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GithubRepositoryCustomProperty do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { property_name: 'test-value', property_type: 'test-value', property_value: ['test-value'], repository: 'test-value' } }

  describe ':github_repository_custom_property' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_custom_property('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'github_repository_custom_property', 'test')
        validate_required_attributes(config, [:property_name, :property_type, :property_value, :repository])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_repository_custom_property('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:github_repository_custom_property)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.github_repository_custom_property('test', required_attrs)

        expect(ref.id).to eq("${github_repository_custom_property.test.id}")
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_custom_property('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'github_repository_custom_property', 'typed')
        expect(config['property_name']).to be_a(String)
        expect(config['property_type']).to be_a(String)
        expect(config['property_value']).to be_a(Array)
        expect(config['repository']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.github_repository_custom_property('first', required_attrs)
        synth.github_repository_custom_property('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'github_repository_custom_property')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :github_repository_custom_property,
    method: :github_repository_custom_property,
    required_attrs: { property_name: 'test-value', property_type: 'test-value', property_value: ['test-value'], repository: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
