# Code generated by pangea-forge.
# InSpec profile for verifying github_enterprise_security_analysis_settings infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set GITHUB_TOKEN and GITHUB_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/github_enterprise_security_analysis_settings/ -t github://

control 'github_enterprise_security_analysis_settings-exists' do
  impact 1.0
  title 'Manages a github_enterprise_security_analysis_settings resource'
  desc 'Verify that the github_enterprise_security_analysis_settings resource exists and has expected properties'

  describe github_enterprise_security_analysis_settings(name: attribute('id')) do
    it { should exist }
    its('enterprise_slug') { should_not be_nil }
  end
end
