# Code generated by pangea-forge.
# InSpec profile for verifying github_emu_group_mapping infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set GITHUB_TOKEN and GITHUB_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/github_emu_group_mapping/ -t github://

control 'github_emu_group_mapping-exists' do
  impact 1.0
  title 'Manages a github_emu_group_mapping resource'
  desc 'Verify that the github_emu_group_mapping resource exists and has expected properties'

  describe github_emu_group_mapping(name: attribute('id')) do
    it { should exist }
    its('group_id') { should_not be_nil }
    its('team_slug') { should_not be_nil }
  end
end
