# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/github_branch_default/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GithubBranchDefault
    include Pangea::Resources::ResourceBuilder

    define_resource :github_branch_default,
      attributes_class: Github::Types::BranchDefaultAttributes,
      outputs: { id: :id },
      map: [:branch, :repository],
      map_bool: [:rename]
  end
  module Github
    include GithubBranchDefault
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Github)
