# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Github::Types
  include Dry.Types()

  class BranchDefaultAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Github::Types

    attribute :branch, T::String
    attribute :repository, T::String
    attribute? :etag, T::String.optional
    attribute? :rename, T::Bool.optional
  end
end
