# Code generated by pangea-forge.
# InSpec profile for verifying github_project_card infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set GITHUB_TOKEN and GITHUB_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/github_project_card/ -t github://

control 'github_project_card-exists' do
  impact 1.0
  title 'Manages a github_project_card resource'
  desc 'Verify that the github_project_card resource exists and has expected properties'

  describe github_project_card(name: attribute('id')) do
    it { should exist }
    its('column_id') { should_not be_nil }
  end
end
